// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutTrackerWebsite.Data;

#nullable disable

namespace WorkoutTrackerWebsite.Migrations
{
    [DbContext(typeof(WorkoutsTrackerDbContext))]
    [Migration("20230407134223_hdfuyer")]
    partial class hdfuyer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.ExerciseCategoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseCategoryModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2572a6d0-5c27-4b95-8239-7a7a60a4a1b6"),
                            Name = "Chest"
                        },
                        new
                        {
                            Id = new Guid("02d2f52f-6337-466d-8c8a-ced042c5d113"),
                            Name = "Shoulder"
                        },
                        new
                        {
                            Id = new Guid("471adc41-5a5c-40a5-afb3-9df9c89d3885"),
                            Name = "Bicep"
                        },
                        new
                        {
                            Id = new Guid("2c4be9e1-4549-423a-9fd1-6812b4ccb079"),
                            Name = "Tricep"
                        },
                        new
                        {
                            Id = new Guid("6d90bcde-7ca9-4091-84af-f5cb0610af5c"),
                            Name = "Legs"
                        },
                        new
                        {
                            Id = new Guid("f0fbbcc4-7fde-42fd-8d59-42969c30d624"),
                            Name = "Back"
                        },
                        new
                        {
                            Id = new Guid("d020d55b-4ca2-4111-875f-63cec2d0ae9c"),
                            Name = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("feb3ee4e-34ec-47ff-98c5-1fd75484ccc1"),
                            Name = "Abs"
                        },
                        new
                        {
                            Id = new Guid("26965982-695a-4be0-a421-6404997a2385"),
                            Name = "Calves"
                        },
                        new
                        {
                            Id = new Guid("235a2992-733c-4eb8-abc1-c7fb74e44924"),
                            Name = "Forearms"
                        });
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.ExerciseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6d27b7ef-2b62-40b6-b19b-f8a85c21fda2"),
                            Category = "Chest",
                            Name = "Bar Dip"
                        },
                        new
                        {
                            Id = new Guid("0248f188-9468-4297-bf24-0f7612ed7828"),
                            Category = "Chest",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = new Guid("599a5e20-d5b8-44c4-a129-88a104005986"),
                            Category = "Chest",
                            Name = "Cable Chest Press"
                        },
                        new
                        {
                            Id = new Guid("7cc0214e-7d7a-41f8-9213-078ada9bf44c"),
                            Category = "Chest",
                            Name = "Close-Grip Bench Press"
                        },
                        new
                        {
                            Id = new Guid("e1b32016-4f46-4de1-bdf7-92c9ac57e874"),
                            Category = "Chest",
                            Name = "Close-Grip Feet-Up Bench Press"
                        },
                        new
                        {
                            Id = new Guid("f43169bc-9d18-40fd-a7d8-9fdd315406d6"),
                            Category = "Chest",
                            Name = "Decline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("0704f35d-86c7-4b8f-a7c9-ecf7d05f96b1"),
                            Category = "Chest",
                            Name = "Dumbbell Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("98d18e69-79d6-4d1d-84d8-0bd7b6680a3b"),
                            Category = "Chest",
                            Name = "Dumbbell Chest Press"
                        },
                        new
                        {
                            Id = new Guid("8e73cbc3-1844-40bb-a762-db9aaa93f9f7"),
                            Category = "Chest",
                            Name = "Dumbbell Decline Chest Press"
                        },
                        new
                        {
                            Id = new Guid("8ff6ed1b-07ea-4d3f-8cca-b1324b0ab0a8"),
                            Category = "Chest",
                            Name = "Dumbbell Floor Press"
                        },
                        new
                        {
                            Id = new Guid("4e423f38-b917-4c89-bca9-eefc745b1d3a"),
                            Category = "Chest",
                            Name = "Dumbbell Pullover"
                        },
                        new
                        {
                            Id = new Guid("8e67c409-6f6d-4800-9c1d-4e30a2d6aef8"),
                            Category = "Chest",
                            Name = "Feet-Up Bench Press"
                        },
                        new
                        {
                            Id = new Guid("6b22e052-3018-40ba-a614-c43782220598"),
                            Category = "Chest",
                            Name = "Floor Press"
                        },
                        new
                        {
                            Id = new Guid("9604965b-4d43-4465-8db4-d3976ecf9de6"),
                            Category = "Chest",
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("8b7be6dc-7326-4c6d-8ca0-8459c3a0d731"),
                            Category = "Chest",
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = new Guid("453ddc99-35d6-4234-8729-f377c3623c21"),
                            Category = "Chest",
                            Name = "Incline Push-Up"
                        },
                        new
                        {
                            Id = new Guid("4a0b381c-60c9-4633-b079-0bcbe3ab9360"),
                            Category = "Chest",
                            Name = "Kneeling Incline Push-Up"
                        },
                        new
                        {
                            Id = new Guid("0215ace6-ff28-480a-8d00-1133ee79954a"),
                            Category = "Chest",
                            Name = "Kneeling Push-Up"
                        },
                        new
                        {
                            Id = new Guid("eca56367-06f6-4bfb-9ee4-c3f8eef6164c"),
                            Category = "Chest",
                            Name = "Machine Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("c8f6d458-dd3d-4b6c-a8b3-6f583e6d8536"),
                            Category = "Chest",
                            Name = "Machine Chest Press"
                        },
                        new
                        {
                            Id = new Guid("ac9f04c3-21ee-4fdd-a52e-e8d6d1db82ac"),
                            Category = "Chest",
                            Name = "Pec Deck"
                        },
                        new
                        {
                            Id = new Guid("63232fc3-66f4-49b8-8020-a83bcd6fc6f2"),
                            Category = "Chest",
                            Name = "Push-Up"
                        },
                        new
                        {
                            Id = new Guid("b5e1b198-0f4b-49d0-8e7d-d371ef58c55c"),
                            Category = "Chest",
                            Name = "Push-Up Against Wall"
                        },
                        new
                        {
                            Id = new Guid("51a200aa-c19a-47db-9b2d-04a3a0bd7934"),
                            Category = "Chest",
                            Name = "Push-Ups With Feet in Rings"
                        },
                        new
                        {
                            Id = new Guid("ce72c72d-abf1-45ac-9cb2-da0397e1e821"),
                            Category = "Chest",
                            Name = "Resistance Band Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("0c37a09f-1307-4cf8-92ce-02b51f933f0b"),
                            Category = "Chest",
                            Name = "Smith Machine Bench Press"
                        },
                        new
                        {
                            Id = new Guid("ca6b608c-758f-4cf1-8fb6-287e04f5dc7f"),
                            Category = "Chest",
                            Name = "Smith Machine Incline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("e9b9ad31-f113-405e-9a0e-fec0b4087b47"),
                            Category = "Chest",
                            Name = "Standing Cable Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("298d8a0c-a808-440d-b1d6-cc086c16e096"),
                            Category = "Shoulder",
                            Name = "Band External Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("fa2e7eea-4363-4b50-9854-848aa4503ebf"),
                            Category = "Shoulder",
                            Name = "Band Internal Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("56505ea3-e2d8-400f-97ec-2de5ff605d14"),
                            Category = "Shoulder",
                            Name = "Band Pull-Apart"
                        },
                        new
                        {
                            Id = new Guid("70d8003d-5822-41a5-ba85-2c1c9cb60285"),
                            Category = "Shoulder",
                            Name = "Barbell Front Raise"
                        },
                        new
                        {
                            Id = new Guid("d26854cf-1b76-4b11-9532-946cf8a926a0"),
                            Category = "Shoulder",
                            Name = "Barbell Rear Delt Row"
                        },
                        new
                        {
                            Id = new Guid("1a3ff088-6926-4f0b-a4a4-39463dff8055"),
                            Category = "Shoulder",
                            Name = "Barbell Upright Row"
                        },
                        new
                        {
                            Id = new Guid("55bd673b-feea-4cf2-b528-632f9ac8426d"),
                            Category = "Shoulder",
                            Name = "Behind the Neck Press"
                        },
                        new
                        {
                            Id = new Guid("259a2373-2156-45ab-a107-e3762fe8e56e"),
                            Category = "Shoulder",
                            Name = "Cable Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("f4ca4434-1a3b-44f1-8ad5-d9e79d7a120a"),
                            Category = "Shoulder",
                            Name = "Cable Rear Delt Row"
                        },
                        new
                        {
                            Id = new Guid("0222036b-36a3-4df6-aab4-4421794b252f"),
                            Category = "Shoulder",
                            Name = "Dumbbell Front Raise"
                        },
                        new
                        {
                            Id = new Guid("0aa229aa-cac7-4353-bfa5-8dede2f6b8ce"),
                            Category = "Shoulder",
                            Name = "Dumbbell Horizontal Internal Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("cd9c5fb5-2323-4fb3-9d9a-a55cae8b1f57"),
                            Category = "Shoulder",
                            Name = "Dumbbell Horizontal External Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("679d5b8a-7ad2-4101-88fb-06c9dbdfa50b"),
                            Category = "Shoulder",
                            Name = "Dumbbell Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("63ec5f44-70a0-4454-8db0-ff083e6577b0"),
                            Category = "Shoulder",
                            Name = "Dumbbell Rear Delt Row"
                        },
                        new
                        {
                            Id = new Guid("808a5fc3-feb6-4a5f-bc8d-b3dac3e6e221"),
                            Category = "Shoulder",
                            Name = "Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("d36f3423-2de6-4a28-a0aa-ee522180c593"),
                            Category = "Shoulder",
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = new Guid("e9f63686-b608-4718-8f97-690f49c19711"),
                            Category = "Shoulder",
                            Name = "Front Hold"
                        },
                        new
                        {
                            Id = new Guid("15b0b134-c83b-4506-9882-6a32de9ec7e1"),
                            Category = "Shoulder",
                            Name = "Lying Dumbbell External Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("e8800d7e-5bca-4b0f-8790-cb2f31566564"),
                            Category = "Shoulder",
                            Name = "Lying Dumbbell Internal Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("c983baa5-90df-4baf-b7be-632edf768e1d"),
                            Category = "Shoulder",
                            Name = "Machine Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("4b0544f5-d6e2-46a6-8d28-8973666a6001"),
                            Category = "Shoulder",
                            Name = "Machine Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("0f559aee-3b37-4050-bbca-f89da9257a02"),
                            Category = "Shoulder",
                            Name = "Monkey Row"
                        },
                        new
                        {
                            Id = new Guid("f785fa6b-3d1f-4675-ba39-22877fbff390"),
                            Category = "Shoulder",
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("85a02468-09a9-42f7-83fc-79d35bfc72bd"),
                            Category = "Shoulder",
                            Name = "Plate Front Raise"
                        },
                        new
                        {
                            Id = new Guid("ae682a05-9ce9-4c32-be58-7b899ca9ba7c"),
                            Category = "Shoulder",
                            Name = "Power Jerk"
                        },
                        new
                        {
                            Id = new Guid("ae5481a2-d132-43c5-9b82-518d00b76e30"),
                            Category = "Shoulder",
                            Name = "Push Press"
                        },
                        new
                        {
                            Id = new Guid("6a204ffa-57cc-49d0-963e-db12deacc34f"),
                            Category = "Shoulder",
                            Name = "Reverse Dumbbell Flyes"
                        },
                        new
                        {
                            Id = new Guid("73ec3926-0b9c-4a8a-9250-5fc4c67c3df0"),
                            Category = "Shoulder",
                            Name = "Reverse Machine Fly"
                        },
                        new
                        {
                            Id = new Guid("29122bb0-1aed-44db-bddd-6bea1eb734ed"),
                            Category = "Shoulder",
                            Name = "Seated Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("aae867d0-87fb-4f91-be20-03402c8e7f90"),
                            Category = "Shoulder",
                            Name = "Seated Barbell Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("35ccf36d-1204-42c2-9d66-db5402be4c10"),
                            Category = "Shoulder",
                            Name = "Seated Smith Machine Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("06a16211-8b80-4a88-96b3-7c669c654d04"),
                            Category = "Shoulder",
                            Name = "Snatch Grip Behind the Neck Press"
                        },
                        new
                        {
                            Id = new Guid("bd8cba3d-9590-4e76-8af7-50f74e9f2d89"),
                            Category = "Shoulder",
                            Name = "Squat Jerk"
                        },
                        new
                        {
                            Id = new Guid("9fad5ea2-212d-4f86-aecd-f2615d2e0b17"),
                            Category = "Shoulder",
                            Name = "Split Jerk"
                        },
                        new
                        {
                            Id = new Guid("f458cf1e-8ba2-4bb2-9eb5-1b1013832909"),
                            Category = "Bicep",
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = new Guid("b00682e5-a149-4c09-9a94-c7024dfb8054"),
                            Category = "Bicep",
                            Name = "Barbell Preacher Curl"
                        },
                        new
                        {
                            Id = new Guid("49809d71-8216-4277-8fe9-1930d0dfc33b"),
                            Category = "Bicep",
                            Name = "Bodyweight Curl"
                        },
                        new
                        {
                            Id = new Guid("649d6070-97b3-46da-841e-9582d4f58deb"),
                            Category = "Bicep",
                            Name = "Cable Curl With Bar"
                        },
                        new
                        {
                            Id = new Guid("c667ad11-e17b-4ec1-b34f-b1952f05990f"),
                            Category = "Bicep",
                            Name = "Cable Curl With Rope"
                        },
                        new
                        {
                            Id = new Guid("98505df8-2f50-4a77-b749-21b3dbd442b6"),
                            Category = "Bicep",
                            Name = "Concentration Curl"
                        },
                        new
                        {
                            Id = new Guid("da9cd73b-ee57-4729-a95a-221781db6d2e"),
                            Category = "Bicep",
                            Name = "Dumbbell Curl"
                        },
                        new
                        {
                            Id = new Guid("269041de-d512-4f6b-a2b7-d1db929e1aea"),
                            Category = "Bicep",
                            Name = "Dumbbell Preacher Curl"
                        },
                        new
                        {
                            Id = new Guid("622f0a34-0fdc-406c-a4cb-f9f8987cf93b"),
                            Category = "Bicep",
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = new Guid("6179a302-43f9-45b8-ad34-6d66704caffb"),
                            Category = "Bicep",
                            Name = "Incline Dumbbell Curl"
                        },
                        new
                        {
                            Id = new Guid("12b8ce45-bc46-4ee1-b23f-3def76440b60"),
                            Category = "Bicep",
                            Name = "Machine Bicep Curl"
                        },
                        new
                        {
                            Id = new Guid("c3950dbc-c466-4e66-b449-7a0f6e0e4dd0"),
                            Category = "Bicep",
                            Name = "Spider Curl"
                        },
                        new
                        {
                            Id = new Guid("be5f2950-66fc-4cc7-b612-3d645cfe9b17"),
                            Category = "Tricep",
                            Name = "Barbell Standing Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("033f796b-c9f7-42b5-af83-ddbc02003f20"),
                            Category = "Tricep",
                            Name = "Barbell Lying Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("76a4c16a-a78f-4a72-967e-01ad2ffa5a6f"),
                            Category = "Tricep",
                            Name = "Bench Dip"
                        },
                        new
                        {
                            Id = new Guid("24fc37aa-4aa4-46d0-9a5e-ed210e73a4c0"),
                            Category = "Tricep",
                            Name = "Close-Grip Push-Up"
                        },
                        new
                        {
                            Id = new Guid("28af3c90-c8b1-4758-a09a-c0b93a349e95"),
                            Category = "Tricep",
                            Name = "Dumbbell Lying Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("880989bb-3b33-43f8-97e4-dad15c42ab26"),
                            Category = "Tricep",
                            Name = "Dumbbell Standing Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("2e3c851d-daf3-4118-9a66-aa91494573c1"),
                            Category = "Tricep",
                            Name = "Overhead Cable Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("060b2bb5-f0af-4b36-b08c-b2079e6fec03"),
                            Category = "Tricep",
                            Name = "Tricep Bodyweight Extension"
                        },
                        new
                        {
                            Id = new Guid("c39cfd00-3693-4f2d-bda8-a8208111ef81"),
                            Category = "Tricep",
                            Name = "Tricep Pushdown With Bar"
                        },
                        new
                        {
                            Id = new Guid("da5852b0-bf47-4c23-9d61-a464e28eacdb"),
                            Category = "Tricep",
                            Name = "Tricep Pushdown With Rope"
                        },
                        new
                        {
                            Id = new Guid("720a4819-f5da-4127-bb6f-ff245c2cfc16"),
                            Category = "Legs",
                            Name = "Air Squat"
                        },
                        new
                        {
                            Id = new Guid("26487bb4-769e-4d99-a2fa-a48b6465f6d7"),
                            Category = "Legs",
                            Name = "Barbell Hack Squat"
                        },
                        new
                        {
                            Id = new Guid("5a86d6fd-b3a9-47c9-9e56-ee7a6bb000ae"),
                            Category = "Legs",
                            Name = "Barbell Lunge"
                        },
                        new
                        {
                            Id = new Guid("7709df31-8d25-4f91-8475-7a0380bd36b0"),
                            Category = "Legs",
                            Name = "Barbell Walking Lunge"
                        },
                        new
                        {
                            Id = new Guid("f12223ad-2596-48b3-8ade-8c95f067594b"),
                            Category = "Legs",
                            Name = "Belt Squat"
                        },
                        new
                        {
                            Id = new Guid("8280524c-1042-4243-9f68-c5c95da46b7f"),
                            Category = "Legs",
                            Name = "Body Weight Lunge"
                        },
                        new
                        {
                            Id = new Guid("b8a79ac9-eebb-431f-8eaa-dbbd876bd033"),
                            Category = "Legs",
                            Name = "Box Squat"
                        },
                        new
                        {
                            Id = new Guid("bad8a179-7645-4f3a-81f4-9e543f13d023"),
                            Category = "Legs",
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = new Guid("7b632d5c-8cfb-4ad5-91c8-2bf930151fad"),
                            Category = "Legs",
                            Name = "Chair Squat"
                        },
                        new
                        {
                            Id = new Guid("4373c62f-753f-4d0b-a8f9-51b8fdec00c3"),
                            Category = "Legs",
                            Name = "Dumbbell Lunge"
                        },
                        new
                        {
                            Id = new Guid("6fdcaaa1-a7b1-4172-bcbb-f73cedb4f344"),
                            Category = "Legs",
                            Name = "Dumbbell Squat"
                        },
                        new
                        {
                            Id = new Guid("03726eb2-7e32-42d3-bba4-3ae5fb7764d8"),
                            Category = "Legs",
                            Name = "Front Squat"
                        },
                        new
                        {
                            Id = new Guid("7a196dc1-5e40-4a31-abf1-24b9c86178b0"),
                            Category = "Legs",
                            Name = "Goblet Squat"
                        },
                        new
                        {
                            Id = new Guid("4f98dcc5-cd34-406a-8d99-b3adb8546e03"),
                            Category = "Legs",
                            Name = "Hack Squat Machine"
                        },
                        new
                        {
                            Id = new Guid("35f49047-b830-46fc-8f38-51b1915c411a"),
                            Category = "Legs",
                            Name = "Half Air Squat"
                        },
                        new
                        {
                            Id = new Guid("bbe2f0f4-c462-413e-a485-444fbffc47cb"),
                            Category = "Legs",
                            Name = "Hip Adduction Machine"
                        },
                        new
                        {
                            Id = new Guid("c7dd0ddd-b9cf-4bd4-bf28-a77cee68c6bd"),
                            Category = "Legs",
                            Name = "Landmine Hack Squat"
                        },
                        new
                        {
                            Id = new Guid("cdecba90-ae0c-4bf5-8a6b-80619a67955a"),
                            Category = "Legs",
                            Name = "Landmine Squat"
                        },
                        new
                        {
                            Id = new Guid("87665102-911f-4bb5-bb7e-054fec1e8f42"),
                            Category = "Legs",
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = new Guid("fc1538ba-15d3-4481-b645-9bfa40dafb00"),
                            Category = "Legs",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = new Guid("938e7597-e563-42e2-b97a-ded9f8de2522"),
                            Category = "Legs",
                            Name = "Lying Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("be3d6103-4ddd-4038-bc25-c0c71c2aa9f9"),
                            Category = "Legs",
                            Name = "Pause Squat"
                        },
                        new
                        {
                            Id = new Guid("ccd165f2-43d3-4c34-9ff7-dfc4d36beda5"),
                            Category = "Legs",
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("e3d2a8c9-d5fa-4481-b54e-693745f23a6f"),
                            Category = "Legs",
                            Name = "Safety Bar Squat"
                        },
                        new
                        {
                            Id = new Guid("9a27b3e0-668d-4b1c-9e7a-026e4fd96d6b"),
                            Category = "Legs",
                            Name = "Seated Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("032cdab2-c090-485a-b3d0-bd3cc90da8f6"),
                            Category = "Legs",
                            Name = "Shallow Body Weight Lunge"
                        },
                        new
                        {
                            Id = new Guid("32b3b45f-09a1-4f81-825f-2e51b308c449"),
                            Category = "Legs",
                            Name = "Side Lunges (Bodyweight)"
                        },
                        new
                        {
                            Id = new Guid("b653c786-efcc-4a0e-9412-6e4e87dd9687"),
                            Category = "Legs",
                            Name = "Smith Machine Squat"
                        },
                        new
                        {
                            Id = new Guid("c87fb273-887a-492b-bc20-bb023fe4b055"),
                            Category = "Legs",
                            Name = "Squat"
                        },
                        new
                        {
                            Id = new Guid("18f01e61-0149-47a6-aa91-78349ab6c04f"),
                            Category = "Legs",
                            Name = "Step Up"
                        },
                        new
                        {
                            Id = new Guid("677f4b25-49ec-47f6-b7de-7b8994013b84"),
                            Category = "Legs",
                            Name = "Step Up"
                        },
                        new
                        {
                            Id = new Guid("2194cf6a-a4b8-4803-9249-e684b2c3747c"),
                            Category = "Back",
                            Name = "Back Extension"
                        },
                        new
                        {
                            Id = new Guid("98964530-3661-4e5d-b14e-9ce74b4df4ea"),
                            Category = "Back",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = new Guid("535009be-d704-4c5f-bae0-69cba4e55166"),
                            Category = "Back",
                            Name = "Barbell Shrug"
                        },
                        new
                        {
                            Id = new Guid("f383a74a-493c-426c-b3ac-bb3e326384c1"),
                            Category = "Back",
                            Name = "Block Snatch"
                        },
                        new
                        {
                            Id = new Guid("daab6946-69e0-49ec-8500-9d84b7da8a8d"),
                            Category = "Back",
                            Name = "Cable Close Grip Seated Row"
                        },
                        new
                        {
                            Id = new Guid("ac739ac7-06f0-4736-b630-168ec001352a"),
                            Category = "Back",
                            Name = "Cable Wide Grip Seated Row"
                        },
                        new
                        {
                            Id = new Guid("d73bf95d-f0a8-4e77-a869-e8291a1777a4"),
                            Category = "Back",
                            Name = "Chin-Up"
                        },
                        new
                        {
                            Id = new Guid("5a8e8733-ba63-4def-9314-b2cd05ab38b4"),
                            Category = "Back",
                            Name = "Clean"
                        },
                        new
                        {
                            Id = new Guid("d9bd925a-595e-4d89-84e7-553620dc4fd3"),
                            Category = "Back",
                            Name = "Clean and Jerk"
                        },
                        new
                        {
                            Id = new Guid("d5fcacb6-0259-4ad6-84c1-69bf2acf8ce3"),
                            Category = "Back",
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = new Guid("573f8478-0c22-49e1-9996-415e00075946"),
                            Category = "Back",
                            Name = "Deficit Deadlift"
                        },
                        new
                        {
                            Id = new Guid("631e21a4-27db-46ff-b74a-b91c45a13d04"),
                            Category = "Back",
                            Name = "Dumbbell Deadlift"
                        },
                        new
                        {
                            Id = new Guid("73383f06-6a8f-42f0-9ba8-0c50b39cc201"),
                            Category = "Back",
                            Name = "Dumbbell Row"
                        },
                        new
                        {
                            Id = new Guid("5139c1a9-3956-48bb-899e-1c031260dfc1"),
                            Category = "Back",
                            Name = "Dumbbell Shrug"
                        },
                        new
                        {
                            Id = new Guid("d9d42020-e49f-41f1-9546-34375b676d32"),
                            Category = "Back",
                            Name = "Floor Back Extension"
                        },
                        new
                        {
                            Id = new Guid("59e863ac-fa57-4dbb-9f1d-4a5902408d10"),
                            Category = "Back",
                            Name = "Good Morning"
                        },
                        new
                        {
                            Id = new Guid("c93b4594-9523-4dd2-8b71-9e9d7832d013"),
                            Category = "Back",
                            Name = "Hang Clean"
                        },
                        new
                        {
                            Id = new Guid("dd01e31c-f163-44da-ba93-54bc896267c5"),
                            Category = "Back",
                            Name = "Hang Power Clean"
                        },
                        new
                        {
                            Id = new Guid("e245381a-add5-4c6c-be12-30dbd03ca99f"),
                            Category = "Back",
                            Name = "Hang Power Snatch"
                        },
                        new
                        {
                            Id = new Guid("4945fe52-da13-44f5-ada4-69626e21eac6"),
                            Category = "Back",
                            Name = "Hang Snatch"
                        },
                        new
                        {
                            Id = new Guid("cfd5cce0-db7b-4f68-af0f-033a7a4f48d1"),
                            Category = "Back",
                            Name = "Inverted Row"
                        },
                        new
                        {
                            Id = new Guid("194c9ccd-8008-4007-ab17-e79229a3da5c"),
                            Category = "Back",
                            Name = "Inverted Row with Underhand Grip"
                        },
                        new
                        {
                            Id = new Guid("081ffe4e-5762-433c-a6fe-ced8c894a15b"),
                            Category = "Back",
                            Name = "Kettlebell Swing"
                        },
                        new
                        {
                            Id = new Guid("f017522b-31e0-425d-a517-c5ec11815f86"),
                            Category = "Back",
                            Name = "Lat Pulldown With Pronated Grip"
                        },
                        new
                        {
                            Id = new Guid("0aaad09e-fb02-417a-92f7-1afc5fd59b66"),
                            Category = "Back",
                            Name = "Lat Pulldown With Supinated Grip"
                        },
                        new
                        {
                            Id = new Guid("96bf0db1-7b12-4a6d-92c7-2ce293ee7903"),
                            Category = "Back",
                            Name = "One-Handed Cable Row"
                        },
                        new
                        {
                            Id = new Guid("62e8474d-4c15-46c9-8a36-62202e70bde3"),
                            Category = "Back",
                            Name = "One-Handed Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("a44c3325-ea47-4088-bcfc-18f29ea52df6"),
                            Category = "Back",
                            Name = "Pause Deadlift"
                        },
                        new
                        {
                            Id = new Guid("ef7376e3-dafc-450a-ba07-a9030f72ee78"),
                            Category = "Back",
                            Name = "Pendlay Row"
                        },
                        new
                        {
                            Id = new Guid("5881489f-b4bc-4b92-9231-4403730bbe89"),
                            Category = "Back",
                            Name = "Power Clean"
                        },
                        new
                        {
                            Id = new Guid("3b7f10ff-2ba7-4dd0-bc4e-8359a3747a51"),
                            Category = "Back",
                            Name = "Power Snatch"
                        },
                        new
                        {
                            Id = new Guid("50251c9e-3b77-4cc1-b578-3aac06e49041"),
                            Category = "Back",
                            Name = "Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("c06021f5-31a5-4c84-aafb-b9a387f5d525"),
                            Category = "Back",
                            Name = "Rack Pull"
                        },
                        new
                        {
                            Id = new Guid("39818d07-7975-487f-bb66-d33d712bce4f"),
                            Category = "Back",
                            Name = "Seal Row"
                        },
                        new
                        {
                            Id = new Guid("cdb2943b-3fa5-46e7-bd00-104ec0cfe349"),
                            Category = "Back",
                            Name = "Seated Machine Row"
                        },
                        new
                        {
                            Id = new Guid("f09b2c68-48c6-4c6e-927c-d365d757345e"),
                            Category = "Back",
                            Name = "Snatch"
                        },
                        new
                        {
                            Id = new Guid("4f1e3579-5506-4084-a7d9-8ec7a31aacdd"),
                            Category = "Back",
                            Name = "Snatch Grip Deadlift"
                        },
                        new
                        {
                            Id = new Guid("a77fea40-5c5c-4d52-98cd-c47533b20a82"),
                            Category = "Back",
                            Name = "Stiff-Legged Deadlift"
                        },
                        new
                        {
                            Id = new Guid("4fd08ade-19ca-4677-99e1-8a2bcbc1f069"),
                            Category = "Back",
                            Name = "Straight Arm Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("d696f588-432b-407e-8531-d6570798fc78"),
                            Category = "Back",
                            Name = "Sumo Deadlift"
                        },
                        new
                        {
                            Id = new Guid("bf91954c-b340-44cf-b61a-c6a5287160eb"),
                            Category = "Back",
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = new Guid("d48088fe-8e78-4633-847e-c2bed09aaa57"),
                            Category = "Back",
                            Name = "Trap Bar Deadlift With High Handles"
                        },
                        new
                        {
                            Id = new Guid("30f00266-c0ea-46f6-b76d-dfab853fe451"),
                            Category = "Back",
                            Name = "Trap Bar Deadlift With Low Handles"
                        },
                        new
                        {
                            Id = new Guid("accee037-bd07-4e56-9460-40d27e401152"),
                            Category = "Glutes",
                            Name = "Banded Side Kicks"
                        },
                        new
                        {
                            Id = new Guid("04e14ab7-025f-41b1-82c8-369404f564c8"),
                            Category = "Glutes",
                            Name = "Cable Pull Through"
                        },
                        new
                        {
                            Id = new Guid("4a8e8379-2352-4ebe-8197-83e2482720e1"),
                            Category = "Glutes",
                            Name = "Clamshells"
                        },
                        new
                        {
                            Id = new Guid("e8c73793-0613-44c4-b063-2354cf20023d"),
                            Category = "Glutes",
                            Name = "Dumbbell Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("3e8efda4-d7e1-4264-a4c4-e2f160c72393"),
                            Category = "Glutes",
                            Name = "Dumbbell Frog Pumps"
                        },
                        new
                        {
                            Id = new Guid("d49083a2-2290-4066-8136-58f63fa1ab0e"),
                            Category = "Glutes",
                            Name = "Fire Hydrants"
                        },
                        new
                        {
                            Id = new Guid("5ca12ebf-2da5-4f56-a63a-705b51c39f73"),
                            Category = "Glutes",
                            Name = "Frog Pumps"
                        },
                        new
                        {
                            Id = new Guid("af56489c-acb8-4ecc-9dd2-7c675aedc548"),
                            Category = "Glutes",
                            Name = "Glute Bridge"
                        },
                        new
                        {
                            Id = new Guid("af8ca9a0-692c-4d92-98c0-c43a88f7b2df"),
                            Category = "Glutes",
                            Name = "Hip Abduction Against Band"
                        },
                        new
                        {
                            Id = new Guid("6fcf5f9f-d754-4f51-a6ef-698324486537"),
                            Category = "Glutes",
                            Name = "Hip Abduction Machine"
                        },
                        new
                        {
                            Id = new Guid("d7bfa5a7-9ef1-457a-9dfe-be5bd97cc3f6"),
                            Category = "Glutes",
                            Name = "Hip Thrust"
                        },
                        new
                        {
                            Id = new Guid("2c21daea-f8dc-4fd9-b1ef-e4fd5a33f465"),
                            Category = "Glutes",
                            Name = "Hip Thrust Machine"
                        },
                        new
                        {
                            Id = new Guid("43616d61-f68f-4a3e-8af0-6ce2358f8355"),
                            Category = "Glutes",
                            Name = "Hip Thrust With Band Around Knees"
                        },
                        new
                        {
                            Id = new Guid("4986cb24-a58c-4b21-8acf-03ed0ea0f384"),
                            Category = "Glutes",
                            Name = "Lateral Walk With Band"
                        },
                        new
                        {
                            Id = new Guid("3dfe86a6-ddfa-4d94-98b4-03d13aad2120"),
                            Category = "Glutes",
                            Name = "Machine Glute Kickbacks"
                        },
                        new
                        {
                            Id = new Guid("5894bb40-d911-45f6-9aad-4156df685f3c"),
                            Category = "Glutes",
                            Name = "One-Legged Glute Bridge"
                        },
                        new
                        {
                            Id = new Guid("c71a207a-36a2-463c-974e-13d891484034"),
                            Category = "Glutes",
                            Name = "One-Legged Hip Thrust"
                        },
                        new
                        {
                            Id = new Guid("af4852c5-2b6a-4a17-87f4-1557c2998c79"),
                            Category = "Glutes",
                            Name = "Single Leg Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("2e6caf4b-d53a-42e0-a1f1-496d6e166789"),
                            Category = "Glutes",
                            Name = "Standing Glute Kickback in Machine"
                        },
                        new
                        {
                            Id = new Guid("92f6981e-b2e7-4b29-bffc-75e3c15b8e00"),
                            Category = "Glutes",
                            Name = "Step Up"
                        },
                        new
                        {
                            Id = new Guid("c33d631f-2eaa-4162-8db1-cac477c402df"),
                            Category = "Abs",
                            Name = "Cable Crunch"
                        },
                        new
                        {
                            Id = new Guid("2e298a85-f43b-4cfe-82dc-1a027ff854d4"),
                            Category = "Abs",
                            Name = "Crunch"
                        },
                        new
                        {
                            Id = new Guid("2fa3226f-0411-40aa-a6ca-7b8e9c3313ac"),
                            Category = "Abs",
                            Name = "Dead Bug"
                        },
                        new
                        {
                            Id = new Guid("a9fc376f-5a8b-4e12-aa7c-12e0a220645a"),
                            Category = "Abs",
                            Name = "Hanging Leg Raise"
                        },
                        new
                        {
                            Id = new Guid("fb39b934-5c1d-457e-a368-11ade8245b28"),
                            Category = "Abs",
                            Name = "Hanging Knee Raise"
                        },
                        new
                        {
                            Id = new Guid("cda30f7e-d64e-43ad-b848-13b95e94e67c"),
                            Category = "Abs",
                            Name = "Hanging Sit-Up"
                        },
                        new
                        {
                            Id = new Guid("0c4a460c-d962-4203-901e-a3046e5fc352"),
                            Category = "Abs",
                            Name = "High to Low Wood Chop with Band"
                        },
                        new
                        {
                            Id = new Guid("5b71e2c0-cfa7-4901-aac7-3b88ad080da9"),
                            Category = "Abs",
                            Name = "Horizontal Wood Chop with Band"
                        },
                        new
                        {
                            Id = new Guid("b39d9afa-725a-465a-901b-7153d632a4bb"),
                            Category = "Abs",
                            Name = "Kneeling Ab Wheel Roll-Out"
                        },
                        new
                        {
                            Id = new Guid("23855965-24e9-4d9f-a1d9-e3a204f5c1df"),
                            Category = "Abs",
                            Name = "Kneeling Plank"
                        },
                        new
                        {
                            Id = new Guid("dcd78369-f4e5-40f9-a05d-e9f42c1a39e1"),
                            Category = "Abs",
                            Name = "Kneeling Side Plank"
                        },
                        new
                        {
                            Id = new Guid("47b85636-6e1b-44eb-89bc-af0afc669a2c"),
                            Category = "Abs",
                            Name = "Lying Leg Raise"
                        },
                        new
                        {
                            Id = new Guid("06b330a7-2a9e-4d1c-be24-9ed4c3b9ca0e"),
                            Category = "Abs",
                            Name = "Lying Windshield Wiper"
                        },
                        new
                        {
                            Id = new Guid("f0a37a9d-37d1-4d46-b2cb-343c3f0a8df3"),
                            Category = "Abs",
                            Name = "Lying Windshield Wiper with Bent Knees"
                        },
                        new
                        {
                            Id = new Guid("1fa57ecf-f9d1-48b0-862c-3d07143087c1"),
                            Category = "Abs",
                            Name = "Machine Crunch"
                        },
                        new
                        {
                            Id = new Guid("9a1dab0b-67dd-4c6a-8d86-58d8b9f3ab19"),
                            Category = "Abs",
                            Name = "Mountain Climbers"
                        },
                        new
                        {
                            Id = new Guid("b25a7b8d-bc9b-42d4-9a23-b4b8f96db4f3"),
                            Category = "Abs",
                            Name = "Oblique Crunch"
                        },
                        new
                        {
                            Id = new Guid("15ce3d6c-3bae-4abc-be01-0845506785a0"),
                            Category = "Abs",
                            Name = "Oblique Sit-Up"
                        },
                        new
                        {
                            Id = new Guid("4eb2154e-7372-445a-8a95-e6b0c4fa8126"),
                            Category = "Abs",
                            Name = "Plank"
                        },
                        new
                        {
                            Id = new Guid("94c74149-e14a-45ce-9b43-aeae096ca045"),
                            Category = "Abs",
                            Name = "Side Plank"
                        },
                        new
                        {
                            Id = new Guid("17a4ef6b-91dd-4756-aa18-5fd162dfefa4"),
                            Category = "Abs",
                            Name = "Sit-Up"
                        },
                        new
                        {
                            Id = new Guid("77a7894b-86ac-41cb-ac06-23cf40b51a1c"),
                            Category = "Calves",
                            Name = "Eccentric Heel Drop"
                        },
                        new
                        {
                            Id = new Guid("176435ca-bdf3-47cf-8e26-33dad33556cb"),
                            Category = "Calves",
                            Name = "Heel Raise"
                        },
                        new
                        {
                            Id = new Guid("bd14fcad-89cd-427c-a44d-96b7a59693fb"),
                            Category = "Calves",
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("3f6a393f-8ba0-4b6e-be12-50b85edce579"),
                            Category = "Calves",
                            Name = "Standing Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("ff352581-a3e0-4474-a261-36d35fffb2a4"),
                            Category = "Forearms",
                            Name = "Barbell Wrist Curl"
                        },
                        new
                        {
                            Id = new Guid("eb97d071-89e8-40e3-8cac-ed6b83adc0b3"),
                            Category = "Forearms",
                            Name = "Barbell Wrist Curl Behind the Back"
                        },
                        new
                        {
                            Id = new Guid("f540f26c-2336-45ce-844f-0de35bee497c"),
                            Category = "Forearms",
                            Name = "Bar Hang"
                        },
                        new
                        {
                            Id = new Guid("af0a8172-321e-4be8-a84d-607761481f1b"),
                            Category = "Forearms",
                            Name = "Dumbbell Wrist Curl"
                        },
                        new
                        {
                            Id = new Guid("6443a5df-cf4f-4817-8cc9-03571c12a3cc"),
                            Category = "Forearms",
                            Name = "Farmers Walk"
                        },
                        new
                        {
                            Id = new Guid("18c46347-7758-47db-b0c8-167f4498c680"),
                            Category = "Forearms",
                            Name = "Fat Bar Deadlift"
                        },
                        new
                        {
                            Id = new Guid("36439254-1f79-4b8f-830d-21c609dc2166"),
                            Category = "Forearms",
                            Name = "Gripper"
                        },
                        new
                        {
                            Id = new Guid("4eff85c8-7330-4ae5-9e6f-85a4fc319f6f"),
                            Category = "Forearms",
                            Name = "One-Handed Bar Hang"
                        },
                        new
                        {
                            Id = new Guid("f9ff0018-df46-4fad-8c93-216c48c5ce59"),
                            Category = "Forearms",
                            Name = "Plate Pinch"
                        },
                        new
                        {
                            Id = new Guid("9574c56c-83ce-47ba-86c9-36cd8d94fca1"),
                            Category = "Forearms",
                            Name = "Plate Wrist Curl"
                        },
                        new
                        {
                            Id = new Guid("58d1d8fb-9768-4158-8ebd-2a55a163c38a"),
                            Category = "Forearms",
                            Name = "Towel Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("fd8c89d4-65a6-4931-aa28-51327cfe980e"),
                            Category = "Forearms",
                            Name = "Barbell Wrist Extension"
                        },
                        new
                        {
                            Id = new Guid("ab5f436f-72fe-45ff-b472-b4b9bd672719"),
                            Category = "Forearms",
                            Name = "Dumbbell Wrist Extension"
                        });
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.LogMessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LogMessages");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.RoundModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.SetModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.UserAchievementsModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MainExercises")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodTraining")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalWeightLifted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalWorkoutSessions")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersAchievements");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.UserFriendsModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FriendsString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersFriends");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutTemplateExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkoutTemplateModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateModelId");

                    b.ToTable("WorkoutTemplateExercises");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutTemplateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.RoundModel", b =>
                {
                    b.HasOne("WorkoutTrackerWebsite.Models.WorkoutModel", "Workout")
                        .WithMany("Rounds")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.SetModel", b =>
                {
                    b.HasOne("WorkoutTrackerWebsite.Models.RoundModel", "Round")
                        .WithMany("Sets")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutTemplateExercise", b =>
                {
                    b.HasOne("WorkoutTrackerWebsite.Models.WorkoutTemplateModel", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.RoundModel", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutModel", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutTemplateModel", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
