// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutTrackerWebsite.Data;

#nullable disable

namespace WorkoutTrackerWebsite.Migrations
{
    [DbContext(typeof(WorkoutsTrackerDbContext))]
    [Migration("20230330202447_kkkhhhh")]
    partial class kkkhhhh
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.ExerciseCategoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseCategoryModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("07d19e75-a2b2-46ab-ae62-0fbe1dc0d08f"),
                            Name = "Chest"
                        },
                        new
                        {
                            Id = new Guid("2503921d-ee23-4e55-bc6d-795c39cf9825"),
                            Name = "Shoulder"
                        },
                        new
                        {
                            Id = new Guid("fe1c79ce-fba3-4b7c-b0e9-0b5af4880831"),
                            Name = "Bicep"
                        },
                        new
                        {
                            Id = new Guid("4288c9fa-8a89-4f74-aba1-18d88abec621"),
                            Name = "Tricep"
                        },
                        new
                        {
                            Id = new Guid("4c23d15c-21e5-4234-954d-e7bf4b65343a"),
                            Name = "Legs"
                        },
                        new
                        {
                            Id = new Guid("45ea0862-ce9f-4aaa-bb1d-0aa815384b30"),
                            Name = "Back"
                        },
                        new
                        {
                            Id = new Guid("dd272e82-83d1-4140-b64b-446e26cb3160"),
                            Name = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("bb183c51-9428-4d5a-9b6b-08892158d890"),
                            Name = "Abs"
                        },
                        new
                        {
                            Id = new Guid("eee0ea8b-004e-4dd2-9b95-6a87d730cafe"),
                            Name = "Calves"
                        },
                        new
                        {
                            Id = new Guid("3302aa3b-86f6-4ecb-b1e6-0b3fc32f3e7b"),
                            Name = "Forearms"
                        });
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.ExerciseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fff6690d-eaa9-4d27-9cbd-57ff2984de01"),
                            Category = "Chest",
                            Name = "Bar Dip"
                        },
                        new
                        {
                            Id = new Guid("b04a2307-cfe9-4a9f-8023-86fc405301ef"),
                            Category = "Chest",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = new Guid("604fea05-65c6-456c-ad41-1ef499916151"),
                            Category = "Chest",
                            Name = "Cable Chest Press"
                        },
                        new
                        {
                            Id = new Guid("7f248de6-7cff-4827-b9c8-e57f267b32e4"),
                            Category = "Chest",
                            Name = "Close-Grip Bench Press"
                        },
                        new
                        {
                            Id = new Guid("a1028368-b3b6-406b-ad10-f0aa9d3cf1f9"),
                            Category = "Chest",
                            Name = "Close-Grip Feet-Up Bench Press"
                        },
                        new
                        {
                            Id = new Guid("4be2baec-2928-48c5-9920-4797fc4c2614"),
                            Category = "Chest",
                            Name = "Decline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("d9e79ca6-ec93-4b63-9b83-12c672ee735a"),
                            Category = "Chest",
                            Name = "Dumbbell Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("979b97f1-9be2-49f8-a692-2a240c904ef8"),
                            Category = "Chest",
                            Name = "Dumbbell Chest Press"
                        },
                        new
                        {
                            Id = new Guid("29650dbb-29e0-4745-8e8b-93824381a5cc"),
                            Category = "Chest",
                            Name = "Dumbbell Decline Chest Press"
                        },
                        new
                        {
                            Id = new Guid("4aea3de8-1d8c-43fa-bebd-cd830e725ca8"),
                            Category = "Chest",
                            Name = "Dumbbell Floor Press"
                        },
                        new
                        {
                            Id = new Guid("6989f571-22ff-4090-8cf0-837063e3a4f7"),
                            Category = "Chest",
                            Name = "Dumbbell Pullover"
                        },
                        new
                        {
                            Id = new Guid("aa5be987-c464-45bf-8f7b-e7aae4f23a51"),
                            Category = "Chest",
                            Name = "Feet-Up Bench Press"
                        },
                        new
                        {
                            Id = new Guid("35fc2633-c611-459f-bfdc-889aa5088a57"),
                            Category = "Chest",
                            Name = "Floor Press"
                        },
                        new
                        {
                            Id = new Guid("0f994db9-aa45-4b78-b87d-cba964345c92"),
                            Category = "Chest",
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("a4c7fab4-263c-41f2-9dff-5ce2a892c6f0"),
                            Category = "Chest",
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = new Guid("01859719-4f07-43d5-811c-32ad2626e53a"),
                            Category = "Chest",
                            Name = "Incline Push-Up"
                        },
                        new
                        {
                            Id = new Guid("45f120fa-a05d-4327-a53e-931d0e17e1ad"),
                            Category = "Chest",
                            Name = "Kneeling Incline Push-Up"
                        },
                        new
                        {
                            Id = new Guid("e0f026a2-d866-4c3a-915c-36be76c94399"),
                            Category = "Chest",
                            Name = "Kneeling Push-Up"
                        },
                        new
                        {
                            Id = new Guid("dc23620b-1e4d-469a-a48e-c299e353b3a7"),
                            Category = "Chest",
                            Name = "Machine Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("c9af03a7-b6e5-4e75-8ca7-ac9950898cbd"),
                            Category = "Chest",
                            Name = "Machine Chest Press"
                        },
                        new
                        {
                            Id = new Guid("c105fbf0-0ecd-47f9-a8e8-71189c9eb77a"),
                            Category = "Chest",
                            Name = "Pec Deck"
                        },
                        new
                        {
                            Id = new Guid("6d99fbbe-fcb9-4be9-91db-9b858c8a37fe"),
                            Category = "Chest",
                            Name = "Push-Up"
                        },
                        new
                        {
                            Id = new Guid("7bd24425-2260-47c8-a506-d1ef92742363"),
                            Category = "Chest",
                            Name = "Push-Up Against Wall"
                        },
                        new
                        {
                            Id = new Guid("ec98ed2b-c04b-47ca-a315-59392f8a5f4a"),
                            Category = "Chest",
                            Name = "Push-Ups With Feet in Rings"
                        },
                        new
                        {
                            Id = new Guid("07f9a3fd-e8c6-48ef-b949-d4abeb7ecf50"),
                            Category = "Chest",
                            Name = "Resistance Band Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("c42796a2-a786-4469-8f8e-42e497284ae7"),
                            Category = "Chest",
                            Name = "Smith Machine Bench Press"
                        },
                        new
                        {
                            Id = new Guid("bb31d734-b515-4e61-ac98-0c5c6eadac95"),
                            Category = "Chest",
                            Name = "Smith Machine Incline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("55a44225-7e6b-4742-9da3-b406958c916b"),
                            Category = "Chest",
                            Name = "Standing Cable Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("6729e31b-4493-4f1c-b2af-322c67f2fdec"),
                            Category = "Shoulder",
                            Name = "Band External Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("5d6e475f-7fbe-4ea1-a812-33afeb14d89d"),
                            Category = "Shoulder",
                            Name = "Band Internal Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("37359a9d-962f-4567-bf46-b93986ecd57c"),
                            Category = "Shoulder",
                            Name = "Band Pull-Apart"
                        },
                        new
                        {
                            Id = new Guid("f114d688-6e7d-4797-b341-09dc6ddb076f"),
                            Category = "Shoulder",
                            Name = "Barbell Front Raise"
                        },
                        new
                        {
                            Id = new Guid("3a4ce8c0-618f-4982-812e-679ba30efcc1"),
                            Category = "Shoulder",
                            Name = "Barbell Rear Delt Row"
                        },
                        new
                        {
                            Id = new Guid("1fd3ac77-a282-4472-9a42-35f7f351dc51"),
                            Category = "Shoulder",
                            Name = "Barbell Upright Row"
                        },
                        new
                        {
                            Id = new Guid("cd969216-7425-4be6-8988-edff7a6d0d4e"),
                            Category = "Shoulder",
                            Name = "Behind the Neck Press"
                        },
                        new
                        {
                            Id = new Guid("56b70393-755f-48ae-a57e-feb84c4a7916"),
                            Category = "Shoulder",
                            Name = "Cable Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("c476fad6-b6ac-4e87-9db2-8ee7807d58c7"),
                            Category = "Shoulder",
                            Name = "Cable Rear Delt Row"
                        },
                        new
                        {
                            Id = new Guid("83fb0397-788d-4d67-b4b3-f4df35f7b234"),
                            Category = "Shoulder",
                            Name = "Dumbbell Front Raise"
                        },
                        new
                        {
                            Id = new Guid("9793e204-a9a7-4842-8d27-692e60ce3f4b"),
                            Category = "Shoulder",
                            Name = "Dumbbell Horizontal Internal Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("b6ba1a3b-a0ac-4629-823d-e2bf9dd00899"),
                            Category = "Shoulder",
                            Name = "Dumbbell Horizontal External Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("d1986555-136a-42ad-ac22-bbd47fe8ef53"),
                            Category = "Shoulder",
                            Name = "Dumbbell Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("342df36c-1530-41c4-bbf7-6c73ad42cee5"),
                            Category = "Shoulder",
                            Name = "Dumbbell Rear Delt Row"
                        },
                        new
                        {
                            Id = new Guid("190dc03d-1c3d-4073-99ab-ba88e5f980e1"),
                            Category = "Shoulder",
                            Name = "Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("17003901-bebf-41df-8a60-6aded3ad19d8"),
                            Category = "Shoulder",
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = new Guid("b5272d9d-566f-46f9-be44-9f6f0c38a581"),
                            Category = "Shoulder",
                            Name = "Front Hold"
                        },
                        new
                        {
                            Id = new Guid("586cb92b-083f-4598-9c47-5827300878b3"),
                            Category = "Shoulder",
                            Name = "Lying Dumbbell External Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("d377d25b-9ef1-4c1f-8fc5-a178f5b62467"),
                            Category = "Shoulder",
                            Name = "Lying Dumbbell Internal Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("725f06a9-6dde-4809-8d54-ef9308172bb5"),
                            Category = "Shoulder",
                            Name = "Machine Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("03b42bc6-6e4a-44e0-b7e2-355e6e81af44"),
                            Category = "Shoulder",
                            Name = "Machine Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("693a9d7b-dd72-40f8-8d39-879f5b8cbc1d"),
                            Category = "Shoulder",
                            Name = "Monkey Row"
                        },
                        new
                        {
                            Id = new Guid("44c24bc3-8ef8-48ee-9491-acac4c963b73"),
                            Category = "Shoulder",
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("26b59f12-9447-4f73-b569-3bded6cae643"),
                            Category = "Shoulder",
                            Name = "Plate Front Raise"
                        },
                        new
                        {
                            Id = new Guid("0b49834b-a648-4ee6-8890-2b262bd4dbb3"),
                            Category = "Shoulder",
                            Name = "Power Jerk"
                        },
                        new
                        {
                            Id = new Guid("77fb1376-5af6-4a11-a580-23355bf39167"),
                            Category = "Shoulder",
                            Name = "Push Press"
                        },
                        new
                        {
                            Id = new Guid("cc0ab1ab-86d0-4ba0-85cc-3f8636ac7de7"),
                            Category = "Shoulder",
                            Name = "Reverse Dumbbell Flyes"
                        },
                        new
                        {
                            Id = new Guid("b6accb22-ab60-4ac6-9af2-d3472af89ee0"),
                            Category = "Shoulder",
                            Name = "Reverse Machine Fly"
                        },
                        new
                        {
                            Id = new Guid("a1ad7065-413d-4e3f-b3bf-b99bfa89aca6"),
                            Category = "Shoulder",
                            Name = "Seated Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("0d7d48fa-8d9b-45ae-af32-e118a8f47fa8"),
                            Category = "Shoulder",
                            Name = "Seated Barbell Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("df311d3f-22a1-4bde-b146-b836878a871d"),
                            Category = "Shoulder",
                            Name = "Seated Smith Machine Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("11b39362-4c5d-46f2-a3ce-fc888973a21b"),
                            Category = "Shoulder",
                            Name = "Snatch Grip Behind the Neck Press"
                        },
                        new
                        {
                            Id = new Guid("8783928c-ac1f-49b4-81a1-eb09ca210855"),
                            Category = "Shoulder",
                            Name = "Squat Jerk"
                        },
                        new
                        {
                            Id = new Guid("e3b285f1-ed0c-4da8-91c0-9ada579798df"),
                            Category = "Shoulder",
                            Name = "Split Jerk"
                        },
                        new
                        {
                            Id = new Guid("e3e3f2b6-9eaf-4ab1-ba96-671792b0484c"),
                            Category = "Bicep",
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = new Guid("1dd6b197-4feb-4940-9146-0f7452a30507"),
                            Category = "Bicep",
                            Name = "Barbell Preacher Curl"
                        },
                        new
                        {
                            Id = new Guid("a2d55bc4-7c80-4152-9f53-bc21a86c1386"),
                            Category = "Bicep",
                            Name = "Bodyweight Curl"
                        },
                        new
                        {
                            Id = new Guid("6daaee04-8c37-40f9-8ba7-3255d9cf4278"),
                            Category = "Bicep",
                            Name = "Cable Curl With Bar"
                        },
                        new
                        {
                            Id = new Guid("f68b49a8-e8e0-4add-be30-18e0c99c1de7"),
                            Category = "Bicep",
                            Name = "Cable Curl With Rope"
                        },
                        new
                        {
                            Id = new Guid("db18f154-c0a5-4b46-b74e-24d8636c1a15"),
                            Category = "Bicep",
                            Name = "Concentration Curl"
                        },
                        new
                        {
                            Id = new Guid("da82bdea-de8c-49ec-b283-0e59a5fc34fe"),
                            Category = "Bicep",
                            Name = "Dumbbell Curl"
                        },
                        new
                        {
                            Id = new Guid("51171bff-a0a8-482d-b377-d2d9993a27eb"),
                            Category = "Bicep",
                            Name = "Dumbbell Preacher Curl"
                        },
                        new
                        {
                            Id = new Guid("bbdca610-41da-46af-b733-47b66e2eecb0"),
                            Category = "Bicep",
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = new Guid("48cd3123-f820-4199-991e-e7f0fb9c7b93"),
                            Category = "Bicep",
                            Name = "Incline Dumbbell Curl"
                        },
                        new
                        {
                            Id = new Guid("bea1d5fe-0fad-47b7-ad1c-388ac761c018"),
                            Category = "Bicep",
                            Name = "Machine Bicep Curl"
                        },
                        new
                        {
                            Id = new Guid("17faec90-514d-4e98-964f-d18b1fce5bd3"),
                            Category = "Bicep",
                            Name = "Spider Curl"
                        },
                        new
                        {
                            Id = new Guid("31e76109-a9c5-44bc-956a-c11271c3e872"),
                            Category = "Tricep",
                            Name = "Barbell Standing Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("59f91571-f7bf-479d-ae12-06796d3eb985"),
                            Category = "Tricep",
                            Name = "Barbell Lying Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("e9e81af5-d4e5-4d67-8fd9-8773a465c17f"),
                            Category = "Tricep",
                            Name = "Bench Dip"
                        },
                        new
                        {
                            Id = new Guid("7261ec97-9464-4ef9-8fba-c7a22d43d327"),
                            Category = "Tricep",
                            Name = "Close-Grip Push-Up"
                        },
                        new
                        {
                            Id = new Guid("cf415f53-906c-494d-943a-c280db08f650"),
                            Category = "Tricep",
                            Name = "Dumbbell Lying Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("ccc1798b-b9d6-4a09-9aed-cd095b96f48d"),
                            Category = "Tricep",
                            Name = "Dumbbell Standing Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("a1848ddb-f28d-4906-a772-c83830450ecf"),
                            Category = "Tricep",
                            Name = "Overhead Cable Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("bef6df04-1693-458c-a000-708a4374f1bd"),
                            Category = "Tricep",
                            Name = "Tricep Bodyweight Extension"
                        },
                        new
                        {
                            Id = new Guid("f12144a3-caae-4231-aa47-8e984fc49d2d"),
                            Category = "Tricep",
                            Name = "Tricep Pushdown With Bar"
                        },
                        new
                        {
                            Id = new Guid("c865a5c4-2adb-4ea1-934a-78fe32936035"),
                            Category = "Tricep",
                            Name = "Tricep Pushdown With Rope"
                        },
                        new
                        {
                            Id = new Guid("32e4df50-238d-447c-9323-5276ecd39013"),
                            Category = "Legs",
                            Name = "Air Squat"
                        },
                        new
                        {
                            Id = new Guid("d554a0b6-9767-4bea-8ebd-0491e119e299"),
                            Category = "Legs",
                            Name = "Barbell Hack Squat"
                        },
                        new
                        {
                            Id = new Guid("b9ac2fca-9293-4da0-b820-d6b5b4a0610e"),
                            Category = "Legs",
                            Name = "Barbell Lunge"
                        },
                        new
                        {
                            Id = new Guid("25d77e05-3162-4cf9-99d4-27ef057299b9"),
                            Category = "Legs",
                            Name = "Barbell Walking Lunge"
                        },
                        new
                        {
                            Id = new Guid("a328c713-ded5-4fa1-b562-7b8cb88a4a51"),
                            Category = "Legs",
                            Name = "Belt Squat"
                        },
                        new
                        {
                            Id = new Guid("8dd10bad-b9b4-4ed5-972f-f68dc182d2da"),
                            Category = "Legs",
                            Name = "Body Weight Lunge"
                        },
                        new
                        {
                            Id = new Guid("ff7f6b93-2cea-4bcc-a33a-443c98fc7bf1"),
                            Category = "Legs",
                            Name = "Box Squat"
                        },
                        new
                        {
                            Id = new Guid("e1383fe3-3f73-457a-8f7f-f0bea7077837"),
                            Category = "Legs",
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = new Guid("9da16b95-f7ac-4128-8a85-85d9c5e07480"),
                            Category = "Legs",
                            Name = "Chair Squat"
                        },
                        new
                        {
                            Id = new Guid("26e8e5c8-1c4c-46e4-a947-5a512e6ba5b2"),
                            Category = "Legs",
                            Name = "Dumbbell Lunge"
                        },
                        new
                        {
                            Id = new Guid("86b5bd18-de54-41b6-bdde-ef582204585a"),
                            Category = "Legs",
                            Name = "Dumbbell Squat"
                        },
                        new
                        {
                            Id = new Guid("2db0f1b0-08b4-42cf-b805-89ebb8b1e962"),
                            Category = "Legs",
                            Name = "Front Squat"
                        },
                        new
                        {
                            Id = new Guid("774a2142-7284-42d0-b83e-d9602c7e85ee"),
                            Category = "Legs",
                            Name = "Goblet Squat"
                        },
                        new
                        {
                            Id = new Guid("9822e0ea-af01-4cb2-9f89-2302da024c41"),
                            Category = "Legs",
                            Name = "Hack Squat Machine"
                        },
                        new
                        {
                            Id = new Guid("9819624f-22f6-43e7-926b-a9b8aa940603"),
                            Category = "Legs",
                            Name = "Half Air Squat"
                        },
                        new
                        {
                            Id = new Guid("644ef566-2ea5-4dd6-b659-a243a625a0fd"),
                            Category = "Legs",
                            Name = "Hip Adduction Machine"
                        },
                        new
                        {
                            Id = new Guid("9af541bf-0d13-4273-aa2a-5dc03ec57cda"),
                            Category = "Legs",
                            Name = "Landmine Hack Squat"
                        },
                        new
                        {
                            Id = new Guid("1d978bc8-fefc-46dd-b668-8a80faad096d"),
                            Category = "Legs",
                            Name = "Landmine Squat"
                        },
                        new
                        {
                            Id = new Guid("2ffc779c-3cf4-46da-ad49-064d65df40fa"),
                            Category = "Legs",
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = new Guid("75fd673e-fd74-486f-93aa-dd9e3653a9c4"),
                            Category = "Legs",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = new Guid("c882feb6-86b6-40cd-b1b4-609920e1eff2"),
                            Category = "Legs",
                            Name = "Lying Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("48207ae5-6ab9-4ae2-a307-db253b4b303a"),
                            Category = "Legs",
                            Name = "Pause Squat"
                        },
                        new
                        {
                            Id = new Guid("8e17f350-b37b-4839-a078-2a1564d801cb"),
                            Category = "Legs",
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("b2d498bf-a623-4c71-8809-3202e56627af"),
                            Category = "Legs",
                            Name = "Safety Bar Squat"
                        },
                        new
                        {
                            Id = new Guid("b34a1fa6-0e13-489f-9fb9-18a2b329fce2"),
                            Category = "Legs",
                            Name = "Seated Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("a566d8d8-6ce3-4f76-9cb1-687f2add5cf8"),
                            Category = "Legs",
                            Name = "Shallow Body Weight Lunge"
                        },
                        new
                        {
                            Id = new Guid("0650fde1-d1ec-44c4-9792-f92f7f5700e2"),
                            Category = "Legs",
                            Name = "Side Lunges (Bodyweight)"
                        },
                        new
                        {
                            Id = new Guid("cbd11a5d-1020-47db-abad-c88405f4d8ef"),
                            Category = "Legs",
                            Name = "Smith Machine Squat"
                        },
                        new
                        {
                            Id = new Guid("68a0f13e-30d8-418d-9cc3-44f775db839c"),
                            Category = "Legs",
                            Name = "Squat"
                        },
                        new
                        {
                            Id = new Guid("3d8ad340-35be-4ef7-b1af-280f75730ed0"),
                            Category = "Legs",
                            Name = "Step Up"
                        },
                        new
                        {
                            Id = new Guid("93b2431a-cf25-469f-8f21-1f45512481b2"),
                            Category = "Legs",
                            Name = "Step Up"
                        },
                        new
                        {
                            Id = new Guid("bedad317-3dbf-4ae1-a2e9-bda84248c38e"),
                            Category = "Back",
                            Name = "Back Extension"
                        },
                        new
                        {
                            Id = new Guid("f36cb40d-08ae-4e57-a775-8caf93490f34"),
                            Category = "Back",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = new Guid("ccbbc91a-662b-4c5a-82d4-a0b8d33ce075"),
                            Category = "Back",
                            Name = "Barbell Shrug"
                        },
                        new
                        {
                            Id = new Guid("dc0fca1c-c4ed-474d-87e6-0a892749a6b9"),
                            Category = "Back",
                            Name = "Block Snatch"
                        },
                        new
                        {
                            Id = new Guid("ef97e075-2268-4870-97f8-efb800211259"),
                            Category = "Back",
                            Name = "Cable Close Grip Seated Row"
                        },
                        new
                        {
                            Id = new Guid("a640258e-88c9-4a4a-bb07-016b9f36f25a"),
                            Category = "Back",
                            Name = "Cable Wide Grip Seated Row"
                        },
                        new
                        {
                            Id = new Guid("c1131acb-b118-4962-9920-13657f3d599f"),
                            Category = "Back",
                            Name = "Chin-Up"
                        },
                        new
                        {
                            Id = new Guid("ddc67dc9-801e-41f1-8652-078b02ee6bb0"),
                            Category = "Back",
                            Name = "Clean"
                        },
                        new
                        {
                            Id = new Guid("e565d1a3-d3fd-4352-ac62-ca9fcb19086d"),
                            Category = "Back",
                            Name = "Clean and Jerk"
                        },
                        new
                        {
                            Id = new Guid("bf25b04d-ca97-47a7-95c2-daf6510e6133"),
                            Category = "Back",
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = new Guid("93dcc050-ca7a-4a57-bf92-fc95ec4027e6"),
                            Category = "Back",
                            Name = "Deficit Deadlift"
                        },
                        new
                        {
                            Id = new Guid("7e0382d6-7238-4e5f-9634-165dfa7532e2"),
                            Category = "Back",
                            Name = "Dumbbell Deadlift"
                        },
                        new
                        {
                            Id = new Guid("95793c8d-33c0-4015-a4fa-3978f05cc7ba"),
                            Category = "Back",
                            Name = "Dumbbell Row"
                        },
                        new
                        {
                            Id = new Guid("6973b0ba-7694-4696-8472-a60cc957eccd"),
                            Category = "Back",
                            Name = "Dumbbell Shrug"
                        },
                        new
                        {
                            Id = new Guid("b66e90aa-063d-48d7-ac45-d0237f105173"),
                            Category = "Back",
                            Name = "Floor Back Extension"
                        },
                        new
                        {
                            Id = new Guid("74776ded-1145-48b2-8c2b-7eb35911d3da"),
                            Category = "Back",
                            Name = "Good Morning"
                        },
                        new
                        {
                            Id = new Guid("2478c022-413f-4823-8c4a-6e0c081c7b17"),
                            Category = "Back",
                            Name = "Hang Clean"
                        },
                        new
                        {
                            Id = new Guid("9b6e7ee2-6dfe-4085-96b7-19ca97a73179"),
                            Category = "Back",
                            Name = "Hang Power Clean"
                        },
                        new
                        {
                            Id = new Guid("e6a98c9f-4b1c-444f-a7e8-ebaea3a22b5d"),
                            Category = "Back",
                            Name = "Hang Power Snatch"
                        },
                        new
                        {
                            Id = new Guid("1a83c430-a1fc-499f-81aa-b29d4689151b"),
                            Category = "Back",
                            Name = "Hang Snatch"
                        },
                        new
                        {
                            Id = new Guid("35f7c5b7-f933-40b1-8a02-2e6a878dcb2f"),
                            Category = "Back",
                            Name = "Inverted Row"
                        },
                        new
                        {
                            Id = new Guid("77f4b2c9-f2ee-42a1-88af-438c7fedf163"),
                            Category = "Back",
                            Name = "Inverted Row with Underhand Grip"
                        },
                        new
                        {
                            Id = new Guid("04da86d4-a67d-4a06-9515-9be5691e2149"),
                            Category = "Back",
                            Name = "Kettlebell Swing"
                        },
                        new
                        {
                            Id = new Guid("2419c863-6fa0-4d59-ae37-380564d6f272"),
                            Category = "Back",
                            Name = "Lat Pulldown With Pronated Grip"
                        },
                        new
                        {
                            Id = new Guid("76fd2121-036f-4fa1-8f7f-49defcc11308"),
                            Category = "Back",
                            Name = "Lat Pulldown With Supinated Grip"
                        },
                        new
                        {
                            Id = new Guid("402393d2-9418-43bd-8b12-2f54f2eb0117"),
                            Category = "Back",
                            Name = "One-Handed Cable Row"
                        },
                        new
                        {
                            Id = new Guid("c5694994-448c-42f2-8f5c-0ca17ab445f7"),
                            Category = "Back",
                            Name = "One-Handed Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("ddf38253-0317-41b3-acf8-8175919cda9a"),
                            Category = "Back",
                            Name = "Pause Deadlift"
                        },
                        new
                        {
                            Id = new Guid("048537d3-13de-4020-b380-f2948ba6f122"),
                            Category = "Back",
                            Name = "Pendlay Row"
                        },
                        new
                        {
                            Id = new Guid("d09d0fc7-8e85-4c58-b73e-d33671d0cc62"),
                            Category = "Back",
                            Name = "Power Clean"
                        },
                        new
                        {
                            Id = new Guid("4bdadacc-ba4b-41e8-9dbf-65b85dd1b66a"),
                            Category = "Back",
                            Name = "Power Snatch"
                        },
                        new
                        {
                            Id = new Guid("6014d1fb-c2be-45cf-aa5b-791b089cfd9f"),
                            Category = "Back",
                            Name = "Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("076ee134-02eb-4889-bc84-3da269548e96"),
                            Category = "Back",
                            Name = "Rack Pull"
                        },
                        new
                        {
                            Id = new Guid("e1711f95-2e4a-462d-a24b-69b57f71aa5f"),
                            Category = "Back",
                            Name = "Seal Row"
                        },
                        new
                        {
                            Id = new Guid("9637a5ae-c481-4359-9eec-85086bedbf84"),
                            Category = "Back",
                            Name = "Seated Machine Row"
                        },
                        new
                        {
                            Id = new Guid("eee44667-fb74-4f3c-bfc1-621444ae75fa"),
                            Category = "Back",
                            Name = "Snatch"
                        },
                        new
                        {
                            Id = new Guid("ea0d45ed-4aa0-4033-85fa-6366cd958418"),
                            Category = "Back",
                            Name = "Snatch Grip Deadlift"
                        },
                        new
                        {
                            Id = new Guid("7e94d909-68eb-42d0-8254-2f428a3d9fec"),
                            Category = "Back",
                            Name = "Stiff-Legged Deadlift"
                        },
                        new
                        {
                            Id = new Guid("67ac78a7-8576-472c-8653-255b397b8eee"),
                            Category = "Back",
                            Name = "Straight Arm Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("c3c8ead7-e00c-473e-9b4f-356cd2cfb99e"),
                            Category = "Back",
                            Name = "Sumo Deadlift"
                        },
                        new
                        {
                            Id = new Guid("c5589cf9-1be5-4a4d-bc33-8acfb67af9d0"),
                            Category = "Back",
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = new Guid("45b4a27a-edbb-43db-b2e3-e75633d9c976"),
                            Category = "Back",
                            Name = "Trap Bar Deadlift With High Handles"
                        },
                        new
                        {
                            Id = new Guid("995e6efc-438f-47ae-a577-256adb72f2ff"),
                            Category = "Back",
                            Name = "Trap Bar Deadlift With Low Handles"
                        },
                        new
                        {
                            Id = new Guid("0e434734-26e2-4854-9df7-caea47ed9a90"),
                            Category = "Glutes",
                            Name = "Banded Side Kicks"
                        },
                        new
                        {
                            Id = new Guid("6e056e2f-6656-40d1-b10b-f4702d5943ae"),
                            Category = "Glutes",
                            Name = "Cable Pull Through"
                        },
                        new
                        {
                            Id = new Guid("9b019f9e-0753-45f0-9829-41cbc8959ec8"),
                            Category = "Glutes",
                            Name = "Clamshells"
                        },
                        new
                        {
                            Id = new Guid("2769a177-0ee0-45f7-9040-48753be7e1c4"),
                            Category = "Glutes",
                            Name = "Dumbbell Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("c4b9ebb1-cee9-4d55-8451-f14531b3d9e4"),
                            Category = "Glutes",
                            Name = "Dumbbell Frog Pumps"
                        },
                        new
                        {
                            Id = new Guid("da66414b-af71-4efb-9f94-4532f8d57679"),
                            Category = "Glutes",
                            Name = "Fire Hydrants"
                        },
                        new
                        {
                            Id = new Guid("f7712579-c71b-41a2-b1f4-d2f185e8b495"),
                            Category = "Glutes",
                            Name = "Frog Pumps"
                        },
                        new
                        {
                            Id = new Guid("a0fcba14-baa2-45df-961e-2de578427574"),
                            Category = "Glutes",
                            Name = "Glute Bridge"
                        },
                        new
                        {
                            Id = new Guid("00aa8d31-b585-4cc8-b8b3-0223f6f59f70"),
                            Category = "Glutes",
                            Name = "Hip Abduction Against Band"
                        },
                        new
                        {
                            Id = new Guid("c28cf495-8b0b-4394-9cd8-939e71f5a3fd"),
                            Category = "Glutes",
                            Name = "Hip Abduction Machine"
                        },
                        new
                        {
                            Id = new Guid("85d619b0-d436-420c-af0a-d9f06f5879fc"),
                            Category = "Glutes",
                            Name = "Hip Thrust"
                        },
                        new
                        {
                            Id = new Guid("c10c8812-3d21-4157-9c12-5c9b9a391c40"),
                            Category = "Glutes",
                            Name = "Hip Thrust Machine"
                        },
                        new
                        {
                            Id = new Guid("9093c728-e92d-44fe-9766-6268dca3744a"),
                            Category = "Glutes",
                            Name = "Hip Thrust With Band Around Knees"
                        },
                        new
                        {
                            Id = new Guid("d162d59c-c658-4c80-8906-ae46d0eab866"),
                            Category = "Glutes",
                            Name = "Lateral Walk With Band"
                        },
                        new
                        {
                            Id = new Guid("f7572984-53a5-4f49-b39b-4cd1dc91099a"),
                            Category = "Glutes",
                            Name = "Machine Glute Kickbacks"
                        },
                        new
                        {
                            Id = new Guid("56fbe0a9-489d-4a30-b20b-d2cd737700f1"),
                            Category = "Glutes",
                            Name = "One-Legged Glute Bridge"
                        },
                        new
                        {
                            Id = new Guid("580b44ad-15ad-40dc-b914-678c3aa8e43d"),
                            Category = "Glutes",
                            Name = "One-Legged Hip Thrust"
                        },
                        new
                        {
                            Id = new Guid("3e73ef88-c89e-46c8-9b00-c0b20ed6750d"),
                            Category = "Glutes",
                            Name = "Single Leg Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("4b89db5c-a358-40e9-bb66-34d1d23b9337"),
                            Category = "Glutes",
                            Name = "Standing Glute Kickback in Machine"
                        },
                        new
                        {
                            Id = new Guid("4a7ce8bb-3fac-4693-af7e-a4e0610d9137"),
                            Category = "Glutes",
                            Name = "Step Up"
                        },
                        new
                        {
                            Id = new Guid("1790d5c1-c270-4c0d-8a3c-245abb2d1f6a"),
                            Category = "Abs",
                            Name = "Cable Crunch"
                        },
                        new
                        {
                            Id = new Guid("e2de4182-8d57-40dd-8d7e-063a994f8914"),
                            Category = "Abs",
                            Name = "Crunch"
                        },
                        new
                        {
                            Id = new Guid("a31e165d-6a79-4fe4-aef0-7b2b73a653df"),
                            Category = "Abs",
                            Name = "Dead Bug"
                        },
                        new
                        {
                            Id = new Guid("255eb60c-d3ae-4ad1-90df-a78aecec7ecb"),
                            Category = "Abs",
                            Name = "Hanging Leg Raise"
                        },
                        new
                        {
                            Id = new Guid("ec9acd3a-1351-4b23-882a-548535323db4"),
                            Category = "Abs",
                            Name = "Hanging Knee Raise"
                        },
                        new
                        {
                            Id = new Guid("6b9476d3-7df7-48c6-a98e-8fc0a67e2843"),
                            Category = "Abs",
                            Name = "Hanging Sit-Up"
                        },
                        new
                        {
                            Id = new Guid("a48cd9d5-6fb1-4d33-950d-b983dde1a63c"),
                            Category = "Abs",
                            Name = "High to Low Wood Chop with Band"
                        },
                        new
                        {
                            Id = new Guid("ebab9d90-d39a-42e9-82b7-24a5b0e99fae"),
                            Category = "Abs",
                            Name = "Horizontal Wood Chop with Band"
                        },
                        new
                        {
                            Id = new Guid("a09c0443-9334-4856-8c6c-41d3b2dd3d89"),
                            Category = "Abs",
                            Name = "Kneeling Ab Wheel Roll-Out"
                        },
                        new
                        {
                            Id = new Guid("e8da6257-b6e7-4be8-bb29-b46e23dc02f7"),
                            Category = "Abs",
                            Name = "Kneeling Plank"
                        },
                        new
                        {
                            Id = new Guid("559f6c61-7375-4557-9634-d7121f5d3a0d"),
                            Category = "Abs",
                            Name = "Kneeling Side Plank"
                        },
                        new
                        {
                            Id = new Guid("b703a12e-db32-4233-92f7-fb4437d9abae"),
                            Category = "Abs",
                            Name = "Lying Leg Raise"
                        },
                        new
                        {
                            Id = new Guid("72bfb545-79ed-49a0-813b-37fcf1248a72"),
                            Category = "Abs",
                            Name = "Lying Windshield Wiper"
                        },
                        new
                        {
                            Id = new Guid("f6946e2d-0e9f-45e4-b8a2-e9ea62946cd3"),
                            Category = "Abs",
                            Name = "Lying Windshield Wiper with Bent Knees"
                        },
                        new
                        {
                            Id = new Guid("ca94c4a1-1621-4c26-8bd1-c0b5520ad763"),
                            Category = "Abs",
                            Name = "Machine Crunch"
                        },
                        new
                        {
                            Id = new Guid("3a863a03-690b-420c-895b-4c330731409c"),
                            Category = "Abs",
                            Name = "Mountain Climbers"
                        },
                        new
                        {
                            Id = new Guid("1ef06462-3a95-4c3e-a001-89ac0f1e1ec2"),
                            Category = "Abs",
                            Name = "Oblique Crunch"
                        },
                        new
                        {
                            Id = new Guid("0711aab7-d62a-48ec-ae5d-0aab326ee3df"),
                            Category = "Abs",
                            Name = "Oblique Sit-Up"
                        },
                        new
                        {
                            Id = new Guid("a2db30fa-e0ed-4d3f-9d76-02990f2cde59"),
                            Category = "Abs",
                            Name = "Plank"
                        },
                        new
                        {
                            Id = new Guid("868f4dbd-5d81-407e-9968-40dfaec9e965"),
                            Category = "Abs",
                            Name = "Side Plank"
                        },
                        new
                        {
                            Id = new Guid("f34a3e42-789c-4c63-b4d0-ff893d70471b"),
                            Category = "Abs",
                            Name = "Sit-Up"
                        },
                        new
                        {
                            Id = new Guid("9bed626c-2a09-4d8b-a345-d60ee837f5c6"),
                            Category = "Calves",
                            Name = "Eccentric Heel Drop"
                        },
                        new
                        {
                            Id = new Guid("daaff0e2-663f-4f70-9a3e-11ad94feead5"),
                            Category = "Calves",
                            Name = "Heel Raise"
                        },
                        new
                        {
                            Id = new Guid("54c99704-32e2-4db3-a97e-ad7b79430d72"),
                            Category = "Calves",
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("e7d59e21-2847-420d-aec4-63a096303c80"),
                            Category = "Calves",
                            Name = "Standing Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("90b898ef-06eb-441e-a9bd-259ec071e3b7"),
                            Category = "Forearms",
                            Name = "Barbell Wrist Curl"
                        },
                        new
                        {
                            Id = new Guid("ce5360a4-82b0-4a84-a202-8f5ccc1b0ece"),
                            Category = "Forearms",
                            Name = "Barbell Wrist Curl Behind the Back"
                        },
                        new
                        {
                            Id = new Guid("2a8e0984-5989-4c5d-9587-ef642d1560cc"),
                            Category = "Forearms",
                            Name = "Bar Hang"
                        },
                        new
                        {
                            Id = new Guid("674a788b-bbc7-445e-a003-20aa12ed820e"),
                            Category = "Forearms",
                            Name = "Dumbbell Wrist Curl"
                        },
                        new
                        {
                            Id = new Guid("94d6d001-6cc8-4ce0-80e8-50077394ee70"),
                            Category = "Forearms",
                            Name = "Farmers Walk"
                        },
                        new
                        {
                            Id = new Guid("ec6dfae4-5e4a-48e4-b606-938356f798be"),
                            Category = "Forearms",
                            Name = "Fat Bar Deadlift"
                        },
                        new
                        {
                            Id = new Guid("dbc11099-e928-4882-8eb6-e9c1b51b083b"),
                            Category = "Forearms",
                            Name = "Gripper"
                        },
                        new
                        {
                            Id = new Guid("2663cf60-788c-459b-a61e-6bf6e2ffa8c5"),
                            Category = "Forearms",
                            Name = "One-Handed Bar Hang"
                        },
                        new
                        {
                            Id = new Guid("a8900063-2f89-4d44-998b-3d303d631f8a"),
                            Category = "Forearms",
                            Name = "Plate Pinch"
                        },
                        new
                        {
                            Id = new Guid("440d64d8-da83-47aa-a708-baf255eb3854"),
                            Category = "Forearms",
                            Name = "Plate Wrist Curl"
                        },
                        new
                        {
                            Id = new Guid("6a1d405b-0cab-425e-a3ad-563642237fc4"),
                            Category = "Forearms",
                            Name = "Towel Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("d3494381-705f-4e58-812c-cb674e16f6ed"),
                            Category = "Forearms",
                            Name = "Barbell Wrist Extension"
                        },
                        new
                        {
                            Id = new Guid("7d5870c4-b539-4ded-9377-8ea025b207ff"),
                            Category = "Forearms",
                            Name = "Dumbbell Wrist Extension"
                        });
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.LogMessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageColor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LogMessages");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.RoundModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.SetModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.UserAchievementsModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MainExercises")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalWeightLifted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalWorkoutSessions")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersAchievements");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.RoundModel", b =>
                {
                    b.HasOne("WorkoutTrackerWebsite.Models.WorkoutModel", "Workout")
                        .WithMany("Rounds")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.SetModel", b =>
                {
                    b.HasOne("WorkoutTrackerWebsite.Models.RoundModel", "Round")
                        .WithMany("Sets")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.RoundModel", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutModel", b =>
                {
                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
