// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutTrackerWebsite.Data;

#nullable disable

namespace WorkoutTrackerWebsite.Migrations
{
    [DbContext(typeof(WorkoutsTrackerDbContext))]
    [Migration("20230330170613_goodorbad")]
    partial class goodorbad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.ExerciseCategoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseCategoryModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6044f227-3cfd-4f9b-ae75-f1170af72cbd"),
                            Name = "Chest"
                        },
                        new
                        {
                            Id = new Guid("7e73d33a-aaeb-4269-bc78-f19fc1704998"),
                            Name = "Shoulder"
                        },
                        new
                        {
                            Id = new Guid("a36ce8dc-90cd-4da7-aac5-8acdb909d59b"),
                            Name = "Bicep"
                        },
                        new
                        {
                            Id = new Guid("eefe92f6-ebaa-4c73-9299-4eb894f7c051"),
                            Name = "Tricep"
                        },
                        new
                        {
                            Id = new Guid("650c7799-d50c-4e74-bab8-a02048466682"),
                            Name = "Legs"
                        },
                        new
                        {
                            Id = new Guid("49cc7000-70a8-4c04-8c40-125905e3d4c1"),
                            Name = "Back"
                        },
                        new
                        {
                            Id = new Guid("936d15f5-cba1-4fcf-98f0-890d0e4041be"),
                            Name = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("6e00939f-73c8-467f-8c65-0ef7e24fb9cb"),
                            Name = "Abs"
                        },
                        new
                        {
                            Id = new Guid("72b7028f-49bf-40c3-9365-407910b4d527"),
                            Name = "Calves"
                        },
                        new
                        {
                            Id = new Guid("609eddf3-a658-4393-b922-db5ac206a7e8"),
                            Name = "Forearms"
                        });
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.ExerciseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3613c8b0-256d-495a-b756-30092c3447cf"),
                            Category = "Chest",
                            Name = "Bar Dip"
                        },
                        new
                        {
                            Id = new Guid("0edf4d7a-9772-4d17-ba79-062e6230cb60"),
                            Category = "Chest",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = new Guid("3ae1e68a-477e-4262-a66e-e31cd3adb077"),
                            Category = "Chest",
                            Name = "Cable Chest Press"
                        },
                        new
                        {
                            Id = new Guid("f9c34bfd-23ae-4bba-ba7e-5a1107a56044"),
                            Category = "Chest",
                            Name = "Close-Grip Bench Press"
                        },
                        new
                        {
                            Id = new Guid("4ee74951-85b6-4c23-99d9-144d24401e57"),
                            Category = "Chest",
                            Name = "Close-Grip Feet-Up Bench Press"
                        },
                        new
                        {
                            Id = new Guid("c630d392-b4f1-462c-9bdb-7c2d9324f528"),
                            Category = "Chest",
                            Name = "Decline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("af6325fd-5b6a-45a1-8dd4-bc0d41d8bcde"),
                            Category = "Chest",
                            Name = "Dumbbell Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("8ee3390f-1000-4f82-b710-be7a0b362dce"),
                            Category = "Chest",
                            Name = "Dumbbell Chest Press"
                        },
                        new
                        {
                            Id = new Guid("47f7c32b-2b2d-4532-a1a0-592c33c95a65"),
                            Category = "Chest",
                            Name = "Dumbbell Decline Chest Press"
                        },
                        new
                        {
                            Id = new Guid("482ef4a9-3a08-4969-8ef8-e54522ca0689"),
                            Category = "Chest",
                            Name = "Dumbbell Floor Press"
                        },
                        new
                        {
                            Id = new Guid("f9b2edb2-95ed-434b-8e39-097b45707fb1"),
                            Category = "Chest",
                            Name = "Dumbbell Pullover"
                        },
                        new
                        {
                            Id = new Guid("bc976696-cbbd-42bd-b2b0-d68b79619734"),
                            Category = "Chest",
                            Name = "Feet-Up Bench Press"
                        },
                        new
                        {
                            Id = new Guid("2ca8d00d-8800-46c6-bc05-b857ced114d9"),
                            Category = "Chest",
                            Name = "Floor Press"
                        },
                        new
                        {
                            Id = new Guid("a9dd989e-42e6-4762-a26e-c8bb6bbc0a78"),
                            Category = "Chest",
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("9d4936d9-9bc4-4323-99fd-c60667115072"),
                            Category = "Chest",
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = new Guid("a944c998-041e-4d28-beee-0c2b50d7dd3b"),
                            Category = "Chest",
                            Name = "Incline Push-Up"
                        },
                        new
                        {
                            Id = new Guid("f07c366e-2da5-4247-9077-b210d5f16559"),
                            Category = "Chest",
                            Name = "Kneeling Incline Push-Up"
                        },
                        new
                        {
                            Id = new Guid("50ee5d09-20be-4aad-915f-6d5d06ef2404"),
                            Category = "Chest",
                            Name = "Kneeling Push-Up"
                        },
                        new
                        {
                            Id = new Guid("6e86b89d-f983-4029-8b1e-1471d441ed62"),
                            Category = "Chest",
                            Name = "Machine Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("bb4e65c1-7838-48f3-bbe4-95ebf74e7860"),
                            Category = "Chest",
                            Name = "Machine Chest Press"
                        },
                        new
                        {
                            Id = new Guid("c73b6abb-d41e-47f3-a853-f7ab889821c2"),
                            Category = "Chest",
                            Name = "Pec Deck"
                        },
                        new
                        {
                            Id = new Guid("786b8120-7b56-4a15-b762-99d09c706abf"),
                            Category = "Chest",
                            Name = "Push-Up"
                        },
                        new
                        {
                            Id = new Guid("acbb9f2e-da5b-489e-93ad-9d3196d3dd9b"),
                            Category = "Chest",
                            Name = "Push-Up Against Wall"
                        },
                        new
                        {
                            Id = new Guid("e09c67df-2dd0-4fda-9554-97f53925aec4"),
                            Category = "Chest",
                            Name = "Push-Ups With Feet in Rings"
                        },
                        new
                        {
                            Id = new Guid("1227d273-8d40-439f-a0c5-f56b3f1e3f61"),
                            Category = "Chest",
                            Name = "Resistance Band Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("526d5acb-895e-4a88-8881-4174e1e58f98"),
                            Category = "Chest",
                            Name = "Smith Machine Bench Press"
                        },
                        new
                        {
                            Id = new Guid("f3d27ef4-e3fc-48a3-a513-0b72379562b8"),
                            Category = "Chest",
                            Name = "Smith Machine Incline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("a9e0d951-5a11-4b10-9060-710516bf422c"),
                            Category = "Chest",
                            Name = "Standing Cable Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("94a5b562-d368-47f1-ab26-95bce9edc5d9"),
                            Category = "Shoulder",
                            Name = "Band External Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("55598cef-fa0c-44c4-9359-08e6f66233df"),
                            Category = "Shoulder",
                            Name = "Band Internal Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("029e1fd9-f4fa-4a3d-8038-cd65fd76c014"),
                            Category = "Shoulder",
                            Name = "Band Pull-Apart"
                        },
                        new
                        {
                            Id = new Guid("5c98f2f8-c5ea-4ebb-bc58-dc1ad2b12fb7"),
                            Category = "Shoulder",
                            Name = "Barbell Front Raise"
                        },
                        new
                        {
                            Id = new Guid("678cfea0-e8fa-4221-9847-f1dee7d3d8b4"),
                            Category = "Shoulder",
                            Name = "Barbell Rear Delt Row"
                        },
                        new
                        {
                            Id = new Guid("4e993101-ea78-43b4-bc4c-3437ce34bfd0"),
                            Category = "Shoulder",
                            Name = "Barbell Upright Row"
                        },
                        new
                        {
                            Id = new Guid("8303bfbe-8a56-4306-8423-2ba4ac6f7d0d"),
                            Category = "Shoulder",
                            Name = "Behind the Neck Press"
                        },
                        new
                        {
                            Id = new Guid("eb40f2ef-e1de-4abd-afb3-8d52d8576c06"),
                            Category = "Shoulder",
                            Name = "Cable Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("7d35909b-17db-4d23-80a4-dac91cafc41d"),
                            Category = "Shoulder",
                            Name = "Cable Rear Delt Row"
                        },
                        new
                        {
                            Id = new Guid("fcaa84af-d8ea-46a6-bbc5-da1c7806d991"),
                            Category = "Shoulder",
                            Name = "Dumbbell Front Raise"
                        },
                        new
                        {
                            Id = new Guid("19335021-26bd-42fd-a4f7-6d4a0d3a338c"),
                            Category = "Shoulder",
                            Name = "Dumbbell Horizontal Internal Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("533c2f51-c323-4033-bdb0-12cb4c3e7c38"),
                            Category = "Shoulder",
                            Name = "Dumbbell Horizontal External Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("87f824ec-5171-4628-862f-edcf4ce94507"),
                            Category = "Shoulder",
                            Name = "Dumbbell Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("8aa0591a-1f0b-4aec-b7cc-c4012fc043e8"),
                            Category = "Shoulder",
                            Name = "Dumbbell Rear Delt Row"
                        },
                        new
                        {
                            Id = new Guid("40500f2c-783d-4b55-881f-ac80e678541e"),
                            Category = "Shoulder",
                            Name = "Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("b5997514-1372-4f68-b240-8ff2c6ff363d"),
                            Category = "Shoulder",
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = new Guid("2623f9d5-e5b8-4ca1-85a6-337673e0ce90"),
                            Category = "Shoulder",
                            Name = "Front Hold"
                        },
                        new
                        {
                            Id = new Guid("c2f6633b-3a4a-43b8-9947-19bdee26b662"),
                            Category = "Shoulder",
                            Name = "Lying Dumbbell External Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("a2394303-dc72-4994-b591-82d5815965c4"),
                            Category = "Shoulder",
                            Name = "Lying Dumbbell Internal Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("a2cb10bd-fb30-44fd-acd6-6dee9e15aa5b"),
                            Category = "Shoulder",
                            Name = "Machine Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("08b55824-6109-4372-8d39-f35e65c7c886"),
                            Category = "Shoulder",
                            Name = "Machine Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("83f1231b-da17-47ff-bf6e-6131deab07b0"),
                            Category = "Shoulder",
                            Name = "Monkey Row"
                        },
                        new
                        {
                            Id = new Guid("0a793c65-446a-4b09-b12a-5faffe10dd22"),
                            Category = "Shoulder",
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("407a793b-10db-4d36-b962-cb038d87af6e"),
                            Category = "Shoulder",
                            Name = "Plate Front Raise"
                        },
                        new
                        {
                            Id = new Guid("5e887fe0-8404-4668-b5f1-6937ec1f8f84"),
                            Category = "Shoulder",
                            Name = "Power Jerk"
                        },
                        new
                        {
                            Id = new Guid("188ab3b0-29b1-4271-b41a-ef1da1ebd8fd"),
                            Category = "Shoulder",
                            Name = "Push Press"
                        },
                        new
                        {
                            Id = new Guid("2dc55bdd-e9ea-4057-adab-97b3712f3779"),
                            Category = "Shoulder",
                            Name = "Reverse Dumbbell Flyes"
                        },
                        new
                        {
                            Id = new Guid("163b130f-c099-4bf0-9dbb-508094ebeed0"),
                            Category = "Shoulder",
                            Name = "Reverse Machine Fly"
                        },
                        new
                        {
                            Id = new Guid("9adadd48-7107-466e-80e3-1657f41e69f6"),
                            Category = "Shoulder",
                            Name = "Seated Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("70872b1f-f01b-410b-b7e2-6b9d2e11bc33"),
                            Category = "Shoulder",
                            Name = "Seated Barbell Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("e061499a-5738-4993-b57e-9118bd52242f"),
                            Category = "Shoulder",
                            Name = "Seated Smith Machine Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("0f784dc4-36c4-46d3-a9e5-e85bc01992d7"),
                            Category = "Shoulder",
                            Name = "Snatch Grip Behind the Neck Press"
                        },
                        new
                        {
                            Id = new Guid("88c48307-0d6d-4313-ba2e-de6db7a2fb46"),
                            Category = "Shoulder",
                            Name = "Squat Jerk"
                        },
                        new
                        {
                            Id = new Guid("131f1a17-ad9e-43a0-8cfb-4febc1c44e80"),
                            Category = "Shoulder",
                            Name = "Split Jerk"
                        },
                        new
                        {
                            Id = new Guid("39749d3b-d734-4f1a-a159-b59c22c79cfa"),
                            Category = "Bicep",
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = new Guid("c739ffee-f0fa-4c2d-b0b6-53edc1baf33b"),
                            Category = "Bicep",
                            Name = "Barbell Preacher Curl"
                        },
                        new
                        {
                            Id = new Guid("22f4fe07-586d-4ae7-a2a1-5dea6bfafc56"),
                            Category = "Bicep",
                            Name = "Bodyweight Curl"
                        },
                        new
                        {
                            Id = new Guid("7c92a5c0-e22c-4222-b9ca-3921d4c0ca0f"),
                            Category = "Bicep",
                            Name = "Cable Curl With Bar"
                        },
                        new
                        {
                            Id = new Guid("d72e0ca8-40c2-4c4a-ae96-2f893ba9415f"),
                            Category = "Bicep",
                            Name = "Cable Curl With Rope"
                        },
                        new
                        {
                            Id = new Guid("71b4a2d8-4755-415c-ae2f-ee3a64955cf3"),
                            Category = "Bicep",
                            Name = "Concentration Curl"
                        },
                        new
                        {
                            Id = new Guid("892f22fa-6b1b-42c2-bc78-dee0e83374e2"),
                            Category = "Bicep",
                            Name = "Dumbbell Curl"
                        },
                        new
                        {
                            Id = new Guid("b99f26f4-4a9e-48fb-b361-3e988bc792b0"),
                            Category = "Bicep",
                            Name = "Dumbbell Preacher Curl"
                        },
                        new
                        {
                            Id = new Guid("ed0fcfb3-6b9d-44ed-ae3c-b63022c67d47"),
                            Category = "Bicep",
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = new Guid("f3e35f40-3887-43d0-a890-b617bc6b1c0f"),
                            Category = "Bicep",
                            Name = "Incline Dumbbell Curl"
                        },
                        new
                        {
                            Id = new Guid("82561a21-ddcc-46b6-b9de-9d6ffbe04c7a"),
                            Category = "Bicep",
                            Name = "Machine Bicep Curl"
                        },
                        new
                        {
                            Id = new Guid("3b6feb44-0c2d-4093-a65c-683e91926841"),
                            Category = "Bicep",
                            Name = "Spider Curl"
                        },
                        new
                        {
                            Id = new Guid("79d6705f-2d9b-42de-8040-5a4d34905f30"),
                            Category = "Tricep",
                            Name = "Barbell Standing Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("439e7db5-c92b-456d-9e3a-888a86c3df9c"),
                            Category = "Tricep",
                            Name = "Barbell Lying Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("1a818793-57aa-4c0f-b5bc-deac638a8aa7"),
                            Category = "Tricep",
                            Name = "Bench Dip"
                        },
                        new
                        {
                            Id = new Guid("f341b504-01d0-4f45-adcc-5f12b3db6a8c"),
                            Category = "Tricep",
                            Name = "Close-Grip Push-Up"
                        },
                        new
                        {
                            Id = new Guid("abe004a2-c979-4109-92bd-e6b1b8576d7a"),
                            Category = "Tricep",
                            Name = "Dumbbell Lying Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("424f6263-19f2-4a1f-8a26-b74719986fc0"),
                            Category = "Tricep",
                            Name = "Dumbbell Standing Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("716d0bd9-8dc4-4cc4-8e30-752fd04084a8"),
                            Category = "Tricep",
                            Name = "Overhead Cable Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("64f6b49e-dfdb-45cb-9e4d-0216bdec4dd7"),
                            Category = "Tricep",
                            Name = "Tricep Bodyweight Extension"
                        },
                        new
                        {
                            Id = new Guid("42ce90d2-844a-465f-88b4-26b022ee98d7"),
                            Category = "Tricep",
                            Name = "Tricep Pushdown With Bar"
                        },
                        new
                        {
                            Id = new Guid("12dabbe5-48b3-4719-8047-de1985f6aa8f"),
                            Category = "Tricep",
                            Name = "Tricep Pushdown With Rope"
                        },
                        new
                        {
                            Id = new Guid("3b22650b-287f-4ecb-8cda-cc19e7b6514c"),
                            Category = "Legs",
                            Name = "Air Squat"
                        },
                        new
                        {
                            Id = new Guid("38a49a2f-0429-48f1-9156-aebaf3bf3bd1"),
                            Category = "Legs",
                            Name = "Barbell Hack Squat"
                        },
                        new
                        {
                            Id = new Guid("6df7049a-9487-4667-8cce-c30ad06bb7c6"),
                            Category = "Legs",
                            Name = "Barbell Lunge"
                        },
                        new
                        {
                            Id = new Guid("dd73057a-c5c4-44b0-906c-0470ce7e04d5"),
                            Category = "Legs",
                            Name = "Barbell Walking Lunge"
                        },
                        new
                        {
                            Id = new Guid("a78752ef-b254-4441-880c-a5615d9fd806"),
                            Category = "Legs",
                            Name = "Belt Squat"
                        },
                        new
                        {
                            Id = new Guid("6add4412-c4a1-4200-82b5-a4ed701a3dc4"),
                            Category = "Legs",
                            Name = "Body Weight Lunge"
                        },
                        new
                        {
                            Id = new Guid("495ce8a9-d210-4f5d-8271-272f1f543507"),
                            Category = "Legs",
                            Name = "Box Squat"
                        },
                        new
                        {
                            Id = new Guid("308f23d0-b6cf-4ee4-91f0-57ce01123fbf"),
                            Category = "Legs",
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = new Guid("7e117529-2687-4788-a784-1e02b390c2f2"),
                            Category = "Legs",
                            Name = "Chair Squat"
                        },
                        new
                        {
                            Id = new Guid("69a9318d-d6d4-4c8f-940a-8090865dbcf4"),
                            Category = "Legs",
                            Name = "Dumbbell Lunge"
                        },
                        new
                        {
                            Id = new Guid("62f8b964-bd2f-4a85-a05c-22117a5c1956"),
                            Category = "Legs",
                            Name = "Dumbbell Squat"
                        },
                        new
                        {
                            Id = new Guid("19ab5b69-c604-4f60-8fdc-7484cba124e2"),
                            Category = "Legs",
                            Name = "Front Squat"
                        },
                        new
                        {
                            Id = new Guid("0db66a5c-8c32-42d2-970b-a680ad7560ee"),
                            Category = "Legs",
                            Name = "Goblet Squat"
                        },
                        new
                        {
                            Id = new Guid("edc222a2-c342-41da-a8e4-3b90ddba3e2d"),
                            Category = "Legs",
                            Name = "Hack Squat Machine"
                        },
                        new
                        {
                            Id = new Guid("e88ea8a2-9e81-4666-97d7-4ae39e9f0db7"),
                            Category = "Legs",
                            Name = "Half Air Squat"
                        },
                        new
                        {
                            Id = new Guid("b9e12429-f422-4fda-9e54-020c32556d74"),
                            Category = "Legs",
                            Name = "Hip Adduction Machine"
                        },
                        new
                        {
                            Id = new Guid("fa1346de-cd16-4b88-a868-3b785f58191e"),
                            Category = "Legs",
                            Name = "Landmine Hack Squat"
                        },
                        new
                        {
                            Id = new Guid("d49bcf8b-7e64-49bb-8d5a-86d8f5bb46ce"),
                            Category = "Legs",
                            Name = "Landmine Squat"
                        },
                        new
                        {
                            Id = new Guid("f43e2ea4-09fc-4924-be25-1ff6062c0ddb"),
                            Category = "Legs",
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = new Guid("a5ca562a-f7db-40f3-93ed-205e74bf0252"),
                            Category = "Legs",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = new Guid("a44e5096-a6c7-4324-99d3-5fcb197c2fbe"),
                            Category = "Legs",
                            Name = "Lying Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("8d7ec38c-11fe-4f40-8e19-d3d80b13044b"),
                            Category = "Legs",
                            Name = "Pause Squat"
                        },
                        new
                        {
                            Id = new Guid("4a857562-0e98-48d8-a91e-4aabca5fd3ed"),
                            Category = "Legs",
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("9f76e667-8ece-46a2-bbfc-aa10b6117281"),
                            Category = "Legs",
                            Name = "Safety Bar Squat"
                        },
                        new
                        {
                            Id = new Guid("94f51fc8-de0b-403d-8dc0-4b951170336c"),
                            Category = "Legs",
                            Name = "Seated Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("9b19f84d-4629-4533-89e1-ad7820d084f8"),
                            Category = "Legs",
                            Name = "Shallow Body Weight Lunge"
                        },
                        new
                        {
                            Id = new Guid("91d9ce83-de20-4416-a10f-d7b85b09156a"),
                            Category = "Legs",
                            Name = "Side Lunges (Bodyweight)"
                        },
                        new
                        {
                            Id = new Guid("ec8bfc2f-bb36-4bff-bdf6-a99051618db4"),
                            Category = "Legs",
                            Name = "Smith Machine Squat"
                        },
                        new
                        {
                            Id = new Guid("2efe0cb1-4b05-4c33-9423-ff995f862efa"),
                            Category = "Legs",
                            Name = "Squat"
                        },
                        new
                        {
                            Id = new Guid("8a3c5a5e-feab-4865-ba21-525b44d10b58"),
                            Category = "Legs",
                            Name = "Step Up"
                        },
                        new
                        {
                            Id = new Guid("b22beb7e-35de-4ce9-8535-4c5e3018a170"),
                            Category = "Legs",
                            Name = "Step Up"
                        },
                        new
                        {
                            Id = new Guid("7016341b-0a84-4438-8ec2-8e684745a458"),
                            Category = "Back",
                            Name = "Back Extension"
                        },
                        new
                        {
                            Id = new Guid("81dc49ff-c496-420e-b21b-b4483ed37111"),
                            Category = "Back",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = new Guid("afff35dd-8f6f-44f6-8976-830a6ca06e08"),
                            Category = "Back",
                            Name = "Barbell Shrug"
                        },
                        new
                        {
                            Id = new Guid("eeefcac2-1ccc-492d-af82-68153305289b"),
                            Category = "Back",
                            Name = "Block Snatch"
                        },
                        new
                        {
                            Id = new Guid("c74354f0-a58f-4fc4-a0a7-8254c9998737"),
                            Category = "Back",
                            Name = "Cable Close Grip Seated Row"
                        },
                        new
                        {
                            Id = new Guid("4f184b2f-e9ea-4a03-ab0a-b8524c5734fa"),
                            Category = "Back",
                            Name = "Cable Wide Grip Seated Row"
                        },
                        new
                        {
                            Id = new Guid("5c4324b5-053a-469c-95db-40ef7297e9c5"),
                            Category = "Back",
                            Name = "Chin-Up"
                        },
                        new
                        {
                            Id = new Guid("8a556523-0059-447c-92ac-3f444d3cc675"),
                            Category = "Back",
                            Name = "Clean"
                        },
                        new
                        {
                            Id = new Guid("1e5b0be8-fbb6-4a3b-92f6-d91d50071e12"),
                            Category = "Back",
                            Name = "Clean and Jerk"
                        },
                        new
                        {
                            Id = new Guid("8fab89f8-2dbd-40ac-9f06-54a38ac508ad"),
                            Category = "Back",
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = new Guid("bd4dc3eb-3b9a-4431-b356-0091507bb6b5"),
                            Category = "Back",
                            Name = "Deficit Deadlift"
                        },
                        new
                        {
                            Id = new Guid("6096f0b7-ed7d-4aea-b234-5f8b43a22235"),
                            Category = "Back",
                            Name = "Dumbbell Deadlift"
                        },
                        new
                        {
                            Id = new Guid("40dc6716-981b-4359-9255-5675f8218b5a"),
                            Category = "Back",
                            Name = "Dumbbell Row"
                        },
                        new
                        {
                            Id = new Guid("aa8d988d-ee47-4eb5-9327-c06fe0733726"),
                            Category = "Back",
                            Name = "Dumbbell Shrug"
                        },
                        new
                        {
                            Id = new Guid("def4ff29-5df3-497b-9be7-12a9f0f27dc6"),
                            Category = "Back",
                            Name = "Floor Back Extension"
                        },
                        new
                        {
                            Id = new Guid("fd993f7d-6b5a-4477-a13f-3f9ccac2ba34"),
                            Category = "Back",
                            Name = "Good Morning"
                        },
                        new
                        {
                            Id = new Guid("b8fe536e-a3f3-4ace-a617-4a3fcb0e41b1"),
                            Category = "Back",
                            Name = "Hang Clean"
                        },
                        new
                        {
                            Id = new Guid("8a85b4ab-593d-4ce6-8ada-75bf38d4926d"),
                            Category = "Back",
                            Name = "Hang Power Clean"
                        },
                        new
                        {
                            Id = new Guid("b43f70a5-1a7b-411f-8d91-6c907a4b506d"),
                            Category = "Back",
                            Name = "Hang Power Snatch"
                        },
                        new
                        {
                            Id = new Guid("697a38bd-b80c-42e4-8f0d-84dfae8ade43"),
                            Category = "Back",
                            Name = "Hang Snatch"
                        },
                        new
                        {
                            Id = new Guid("e9517a56-f42d-4a48-bba3-d792b8b76c1f"),
                            Category = "Back",
                            Name = "Inverted Row"
                        },
                        new
                        {
                            Id = new Guid("d9024d38-563a-4579-b4a8-743e596b9de0"),
                            Category = "Back",
                            Name = "Inverted Row with Underhand Grip"
                        },
                        new
                        {
                            Id = new Guid("4e28e902-dd46-4570-b6fa-4ba7270fa706"),
                            Category = "Back",
                            Name = "Kettlebell Swing"
                        },
                        new
                        {
                            Id = new Guid("9fd9fcbf-1bc3-4e73-9a36-05d2f97e6b1d"),
                            Category = "Back",
                            Name = "Lat Pulldown With Pronated Grip"
                        },
                        new
                        {
                            Id = new Guid("07108d94-e307-4228-aba3-7daecc1a0c56"),
                            Category = "Back",
                            Name = "Lat Pulldown With Supinated Grip"
                        },
                        new
                        {
                            Id = new Guid("8aecb487-4b8d-4ecc-b297-8043672d7db6"),
                            Category = "Back",
                            Name = "One-Handed Cable Row"
                        },
                        new
                        {
                            Id = new Guid("7c1548b0-515f-49c8-9198-79deebb10010"),
                            Category = "Back",
                            Name = "One-Handed Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("ad17eaeb-3af0-4b7f-9022-30e835aed98a"),
                            Category = "Back",
                            Name = "Pause Deadlift"
                        },
                        new
                        {
                            Id = new Guid("956f2676-1435-4c83-bfa5-12057e02c46e"),
                            Category = "Back",
                            Name = "Pendlay Row"
                        },
                        new
                        {
                            Id = new Guid("c5d9b183-9d56-4a7f-8e6f-713325ea63d7"),
                            Category = "Back",
                            Name = "Power Clean"
                        },
                        new
                        {
                            Id = new Guid("c4e08791-26b7-4c23-bc61-ea8eb00ee9f9"),
                            Category = "Back",
                            Name = "Power Snatch"
                        },
                        new
                        {
                            Id = new Guid("0041fb3a-5dc0-4d6c-9b8f-ec239ea01d06"),
                            Category = "Back",
                            Name = "Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("f1a2b909-ebde-4660-964b-42b938256c57"),
                            Category = "Back",
                            Name = "Rack Pull"
                        },
                        new
                        {
                            Id = new Guid("c11fe583-4f37-415f-b902-41fdd80eff31"),
                            Category = "Back",
                            Name = "Seal Row"
                        },
                        new
                        {
                            Id = new Guid("6a29d4b5-6c24-45c5-88c0-b53b7831b81a"),
                            Category = "Back",
                            Name = "Seated Machine Row"
                        },
                        new
                        {
                            Id = new Guid("a92545f1-0889-4439-a2b3-ed9d46f2f25c"),
                            Category = "Back",
                            Name = "Snatch"
                        },
                        new
                        {
                            Id = new Guid("ced02723-3548-400e-b2af-fc67aab1bd12"),
                            Category = "Back",
                            Name = "Snatch Grip Deadlift"
                        },
                        new
                        {
                            Id = new Guid("ad4c3dea-aa73-41cc-8638-8a51735e751b"),
                            Category = "Back",
                            Name = "Stiff-Legged Deadlift"
                        },
                        new
                        {
                            Id = new Guid("12482f73-8b91-406f-8078-9046792eeac7"),
                            Category = "Back",
                            Name = "Straight Arm Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("e53afb17-5d09-4e5e-8387-e6440cd4347e"),
                            Category = "Back",
                            Name = "Sumo Deadlift"
                        },
                        new
                        {
                            Id = new Guid("5ec3b754-2b94-4540-b188-f43fb649b118"),
                            Category = "Back",
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = new Guid("3b05da29-47a4-40a3-9b1c-4e386502f3bd"),
                            Category = "Back",
                            Name = "Trap Bar Deadlift With High Handles"
                        },
                        new
                        {
                            Id = new Guid("1658f996-1108-4377-a1ea-d7e40836b191"),
                            Category = "Back",
                            Name = "Trap Bar Deadlift With Low Handles"
                        },
                        new
                        {
                            Id = new Guid("3d5a5372-fc1c-42af-a338-e6eda0348dc5"),
                            Category = "Glutes",
                            Name = "Banded Side Kicks"
                        },
                        new
                        {
                            Id = new Guid("149b25d0-c31f-4638-aee4-ce8be4680c31"),
                            Category = "Glutes",
                            Name = "Cable Pull Through"
                        },
                        new
                        {
                            Id = new Guid("72ad5183-d6fa-4ca1-9374-be6cf1216921"),
                            Category = "Glutes",
                            Name = "Clamshells"
                        },
                        new
                        {
                            Id = new Guid("3e5584c9-eb22-44a9-9fc4-75464a18d16e"),
                            Category = "Glutes",
                            Name = "Dumbbell Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("d959e638-fffe-4a8c-ac43-c03834343d94"),
                            Category = "Glutes",
                            Name = "Dumbbell Frog Pumps"
                        },
                        new
                        {
                            Id = new Guid("34a5978f-970e-47d2-811f-393e63b6d9ee"),
                            Category = "Glutes",
                            Name = "Fire Hydrants"
                        },
                        new
                        {
                            Id = new Guid("790bfde1-773f-4b75-9ced-7ad9d86adf55"),
                            Category = "Glutes",
                            Name = "Frog Pumps"
                        },
                        new
                        {
                            Id = new Guid("487a2173-1a1a-41c3-80bf-b85b898c17fa"),
                            Category = "Glutes",
                            Name = "Glute Bridge"
                        },
                        new
                        {
                            Id = new Guid("bb6fde02-9aea-4ad2-9084-9da790f3b5ac"),
                            Category = "Glutes",
                            Name = "Hip Abduction Against Band"
                        },
                        new
                        {
                            Id = new Guid("f124e591-7c77-49b9-a330-2071ed24afdc"),
                            Category = "Glutes",
                            Name = "Hip Abduction Machine"
                        },
                        new
                        {
                            Id = new Guid("55af9be8-2390-4f6c-8c74-4d04e9fe3920"),
                            Category = "Glutes",
                            Name = "Hip Thrust"
                        },
                        new
                        {
                            Id = new Guid("180d59c8-2b98-401b-9ceb-37f591a238a5"),
                            Category = "Glutes",
                            Name = "Hip Thrust Machine"
                        },
                        new
                        {
                            Id = new Guid("fde9b6a4-5ae3-4974-98f2-a480d05f8538"),
                            Category = "Glutes",
                            Name = "Hip Thrust With Band Around Knees"
                        },
                        new
                        {
                            Id = new Guid("7bda4894-b399-4160-911f-75a63a794ff7"),
                            Category = "Glutes",
                            Name = "Lateral Walk With Band"
                        },
                        new
                        {
                            Id = new Guid("d2c0ddde-368f-42b0-9fab-8694198bff07"),
                            Category = "Glutes",
                            Name = "Machine Glute Kickbacks"
                        },
                        new
                        {
                            Id = new Guid("45d7658c-f2a0-48e3-868e-e820abe6864f"),
                            Category = "Glutes",
                            Name = "One-Legged Glute Bridge"
                        },
                        new
                        {
                            Id = new Guid("ac1701ee-8454-4219-8b1a-4b8421b3a3e6"),
                            Category = "Glutes",
                            Name = "One-Legged Hip Thrust"
                        },
                        new
                        {
                            Id = new Guid("cf66f399-f4de-451c-a588-a30971975e2b"),
                            Category = "Glutes",
                            Name = "Single Leg Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("07847076-96e5-4369-8c1f-7dfb05d564b4"),
                            Category = "Glutes",
                            Name = "Standing Glute Kickback in Machine"
                        },
                        new
                        {
                            Id = new Guid("19fba112-8872-4164-b0a6-d698d7bf1d32"),
                            Category = "Glutes",
                            Name = "Step Up"
                        },
                        new
                        {
                            Id = new Guid("3b9dd33b-558c-44bc-9e8c-bc63fe87ba08"),
                            Category = "Abs",
                            Name = "Cable Crunch"
                        },
                        new
                        {
                            Id = new Guid("61b747cc-1bcd-48a5-9ee4-aa15a21c097f"),
                            Category = "Abs",
                            Name = "Crunch"
                        },
                        new
                        {
                            Id = new Guid("05e68089-801c-4d4b-a2b1-d53dde6c3f12"),
                            Category = "Abs",
                            Name = "Dead Bug"
                        },
                        new
                        {
                            Id = new Guid("87de685b-b06c-4223-ac6e-cf9650f4d325"),
                            Category = "Abs",
                            Name = "Hanging Leg Raise"
                        },
                        new
                        {
                            Id = new Guid("ceb5871e-b02f-4fb4-8bd7-e7a0d1e5c6b0"),
                            Category = "Abs",
                            Name = "Hanging Knee Raise"
                        },
                        new
                        {
                            Id = new Guid("a013216b-4944-458f-a346-32cd7c6bc4f0"),
                            Category = "Abs",
                            Name = "Hanging Sit-Up"
                        },
                        new
                        {
                            Id = new Guid("13a96737-828a-46b2-8375-af359f79361c"),
                            Category = "Abs",
                            Name = "High to Low Wood Chop with Band"
                        },
                        new
                        {
                            Id = new Guid("dec7548f-41c1-4559-b731-6f1885db8097"),
                            Category = "Abs",
                            Name = "Horizontal Wood Chop with Band"
                        },
                        new
                        {
                            Id = new Guid("71a4d279-835c-4d78-9904-6b8af1edc55e"),
                            Category = "Abs",
                            Name = "Kneeling Ab Wheel Roll-Out"
                        },
                        new
                        {
                            Id = new Guid("495de907-f723-45e9-bc2c-16781e62aa36"),
                            Category = "Abs",
                            Name = "Kneeling Plank"
                        },
                        new
                        {
                            Id = new Guid("565bbe8f-b0ba-4c86-b6fd-d963aa7af803"),
                            Category = "Abs",
                            Name = "Kneeling Side Plank"
                        },
                        new
                        {
                            Id = new Guid("34266793-ce80-4a0e-8299-32ee382fcd3e"),
                            Category = "Abs",
                            Name = "Lying Leg Raise"
                        },
                        new
                        {
                            Id = new Guid("5af55993-f90a-401e-b3ad-9232f7694524"),
                            Category = "Abs",
                            Name = "Lying Windshield Wiper"
                        },
                        new
                        {
                            Id = new Guid("70b0ce15-698a-444c-b3ed-e88a994208c5"),
                            Category = "Abs",
                            Name = "Lying Windshield Wiper with Bent Knees"
                        },
                        new
                        {
                            Id = new Guid("2fce68b6-5dd7-40fa-8994-f55619d2010d"),
                            Category = "Abs",
                            Name = "Machine Crunch"
                        },
                        new
                        {
                            Id = new Guid("4fa41256-c50d-4aaa-a701-55ff50115c38"),
                            Category = "Abs",
                            Name = "Mountain Climbers"
                        },
                        new
                        {
                            Id = new Guid("43e2d1f6-4c8b-4beb-893c-b24d63ee00f7"),
                            Category = "Abs",
                            Name = "Oblique Crunch"
                        },
                        new
                        {
                            Id = new Guid("4688330e-7874-4e45-8000-9efc7d671121"),
                            Category = "Abs",
                            Name = "Oblique Sit-Up"
                        },
                        new
                        {
                            Id = new Guid("8c22e5e7-2a84-4ffc-b7b6-977e3b7895f3"),
                            Category = "Abs",
                            Name = "Plank"
                        },
                        new
                        {
                            Id = new Guid("903efb06-27d8-4614-9766-81efe0a07bee"),
                            Category = "Abs",
                            Name = "Side Plank"
                        },
                        new
                        {
                            Id = new Guid("2a65fc6d-dabc-4163-a986-981ade9dd12e"),
                            Category = "Abs",
                            Name = "Sit-Up"
                        },
                        new
                        {
                            Id = new Guid("b59827cb-533b-4bcd-8031-a29343b5f607"),
                            Category = "Calves",
                            Name = "Eccentric Heel Drop"
                        },
                        new
                        {
                            Id = new Guid("3d6318fe-2edb-450d-b6d8-f7440ff9b773"),
                            Category = "Calves",
                            Name = "Heel Raise"
                        },
                        new
                        {
                            Id = new Guid("8baedd5e-53de-45de-b5a5-120398556c3a"),
                            Category = "Calves",
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("08f05cf5-8305-4a6d-a418-604485cdec7c"),
                            Category = "Calves",
                            Name = "Standing Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("8c405160-9d44-4ab1-ad5c-de1282b202b2"),
                            Category = "Forearms",
                            Name = "Barbell Wrist Curl"
                        },
                        new
                        {
                            Id = new Guid("e0f0f6ac-5d8d-49b1-ac0f-3c021a7ad4d3"),
                            Category = "Forearms",
                            Name = "Barbell Wrist Curl Behind the Back"
                        },
                        new
                        {
                            Id = new Guid("f57aec81-a2bb-4f81-b2d2-8d0643b0a327"),
                            Category = "Forearms",
                            Name = "Bar Hang"
                        },
                        new
                        {
                            Id = new Guid("93956123-627c-440e-bf34-9d973760020c"),
                            Category = "Forearms",
                            Name = "Dumbbell Wrist Curl"
                        },
                        new
                        {
                            Id = new Guid("08cea3e2-7fbd-4e37-a2b3-d54bdd6362b9"),
                            Category = "Forearms",
                            Name = "Farmers Walk"
                        },
                        new
                        {
                            Id = new Guid("d5a3606d-9141-4ed6-a541-0ba8bde25ff0"),
                            Category = "Forearms",
                            Name = "Fat Bar Deadlift"
                        },
                        new
                        {
                            Id = new Guid("f581c6a2-0c0f-408f-ada2-15c4163949a1"),
                            Category = "Forearms",
                            Name = "Gripper"
                        },
                        new
                        {
                            Id = new Guid("5870145d-924a-40f2-8683-b9e78c8257fb"),
                            Category = "Forearms",
                            Name = "One-Handed Bar Hang"
                        },
                        new
                        {
                            Id = new Guid("a27ca2f9-993c-484c-9cbc-a8e4e88cf0ed"),
                            Category = "Forearms",
                            Name = "Plate Pinch"
                        },
                        new
                        {
                            Id = new Guid("0b6b54a3-24d4-4ed3-b511-ea949e261688"),
                            Category = "Forearms",
                            Name = "Plate Wrist Curl"
                        },
                        new
                        {
                            Id = new Guid("e6ee7b66-1ec8-47ea-bcb8-87baa1fa213b"),
                            Category = "Forearms",
                            Name = "Towel Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("4d0ea263-0c27-4778-b2d0-2a518f81abc6"),
                            Category = "Forearms",
                            Name = "Barbell Wrist Extension"
                        },
                        new
                        {
                            Id = new Guid("19d64060-7ea8-4531-9bc8-0dbf8639b326"),
                            Category = "Forearms",
                            Name = "Dumbbell Wrist Extension"
                        });
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.LogMessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsGood")
                        .HasColumnType("bit");

                    b.Property<string>("MessageBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LogMessages");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.RoundModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.SetModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.UserAchievementsModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("MainExercises")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalWeightLifted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalWorkoutSessions")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersAchievements");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.RoundModel", b =>
                {
                    b.HasOne("WorkoutTrackerWebsite.Models.WorkoutModel", "Workout")
                        .WithMany("Rounds")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.SetModel", b =>
                {
                    b.HasOne("WorkoutTrackerWebsite.Models.RoundModel", "Round")
                        .WithMany("Sets")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.RoundModel", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutModel", b =>
                {
                    b.Navigation("Rounds");
                });
#pragma warning restore 612, 618
        }
    }
}
