// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkoutTrackerWebsite.Data;

#nullable disable

namespace WorkoutTrackerWebsite.Migrations
{
    [DbContext(typeof(WorkoutsTrackerDbContext))]
    partial class WorkoutsTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.ExerciseCategoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseCategoryModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f8016bc0-2aed-491f-bd90-aa871f848590"),
                            Name = "Chest"
                        },
                        new
                        {
                            Id = new Guid("8dd92cbc-4b24-4029-8dd2-c0763b8c8dea"),
                            Name = "Shoulder"
                        },
                        new
                        {
                            Id = new Guid("bd55e67d-bc0e-42f3-b383-39fc58b5aaea"),
                            Name = "Bicep"
                        },
                        new
                        {
                            Id = new Guid("471dc78d-ccec-4f7d-8175-ee1be9533f99"),
                            Name = "Tricep"
                        },
                        new
                        {
                            Id = new Guid("6f10ee07-f7de-42b3-a697-a44f30666606"),
                            Name = "Legs"
                        },
                        new
                        {
                            Id = new Guid("2ec41abb-d87d-4bbf-a682-22da9e43eea5"),
                            Name = "Back"
                        },
                        new
                        {
                            Id = new Guid("c0fed27a-1f10-40a0-806c-a5551b765304"),
                            Name = "Glutes"
                        },
                        new
                        {
                            Id = new Guid("c9a03327-6e38-4b56-a0a9-c728c875e265"),
                            Name = "Abs"
                        },
                        new
                        {
                            Id = new Guid("39ddfaa1-77b3-4df0-9650-b3a90163a7e0"),
                            Name = "Calves"
                        },
                        new
                        {
                            Id = new Guid("0d5ab2a2-14b0-4fd2-a18c-33166c77e5f3"),
                            Name = "Forearms"
                        });
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.ExerciseModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("bd2eae5a-2c0c-47fd-b353-fb084bf099e5"),
                            Category = "Chest",
                            Name = "Bar Dip"
                        },
                        new
                        {
                            Id = new Guid("34af233b-3b87-4c99-a036-9a55caa608fa"),
                            Category = "Chest",
                            Name = "Bench Press"
                        },
                        new
                        {
                            Id = new Guid("9f228b96-a8a7-485b-89f4-ecde1a147cf1"),
                            Category = "Chest",
                            Name = "Cable Chest Press"
                        },
                        new
                        {
                            Id = new Guid("be612f94-39ef-422d-87e1-e2b12908924f"),
                            Category = "Chest",
                            Name = "Close-Grip Bench Press"
                        },
                        new
                        {
                            Id = new Guid("f6fe6034-bd95-4506-b5a1-9d673cbe6d88"),
                            Category = "Chest",
                            Name = "Close-Grip Feet-Up Bench Press"
                        },
                        new
                        {
                            Id = new Guid("4204f089-8f91-45db-b039-0eb86d729a27"),
                            Category = "Chest",
                            Name = "Decline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("dea1687f-47ca-4004-8b9d-1c014b3a3fa0"),
                            Category = "Chest",
                            Name = "Dumbbell Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("5e0a1428-9bba-4c70-b778-a05e4cfab3d5"),
                            Category = "Chest",
                            Name = "Dumbbell Chest Press"
                        },
                        new
                        {
                            Id = new Guid("b5136d65-f174-4650-8ad8-adc208c45957"),
                            Category = "Chest",
                            Name = "Dumbbell Decline Chest Press"
                        },
                        new
                        {
                            Id = new Guid("15cd1615-f73c-415d-a1bb-ceba757b043e"),
                            Category = "Chest",
                            Name = "Dumbbell Floor Press"
                        },
                        new
                        {
                            Id = new Guid("4d616183-6757-47d9-8e19-21c902610d84"),
                            Category = "Chest",
                            Name = "Dumbbell Pullover"
                        },
                        new
                        {
                            Id = new Guid("1072898d-93b4-4332-95b5-81fce1467d66"),
                            Category = "Chest",
                            Name = "Feet-Up Bench Press"
                        },
                        new
                        {
                            Id = new Guid("d80ea772-6a29-43b9-8f2e-709c651977b3"),
                            Category = "Chest",
                            Name = "Floor Press"
                        },
                        new
                        {
                            Id = new Guid("8f88700c-c1d4-4c19-9b22-5d6e6777ffb8"),
                            Category = "Chest",
                            Name = "Incline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("70b55350-7876-4940-a41b-d34790a3dcba"),
                            Category = "Chest",
                            Name = "Incline Dumbbell Press"
                        },
                        new
                        {
                            Id = new Guid("efcb9aa0-61aa-4d65-b5f9-ac2856166407"),
                            Category = "Chest",
                            Name = "Incline Push-Up"
                        },
                        new
                        {
                            Id = new Guid("62f09e36-dcd6-4dba-a666-8f504e24d3cb"),
                            Category = "Chest",
                            Name = "Kneeling Incline Push-Up"
                        },
                        new
                        {
                            Id = new Guid("8bcdaf36-c439-42d6-85b3-9b1afd4ececf"),
                            Category = "Chest",
                            Name = "Kneeling Push-Up"
                        },
                        new
                        {
                            Id = new Guid("c674aff0-dafd-47bf-981f-1cf9030819ba"),
                            Category = "Chest",
                            Name = "Machine Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("2f6ce80f-5080-48ad-bb8d-2be634b6b736"),
                            Category = "Chest",
                            Name = "Machine Chest Press"
                        },
                        new
                        {
                            Id = new Guid("79679e9e-64bb-44ae-a847-13c11bf51737"),
                            Category = "Chest",
                            Name = "Pec Deck"
                        },
                        new
                        {
                            Id = new Guid("83227b67-d8a9-48a4-8974-7dc9a0cbc163"),
                            Category = "Chest",
                            Name = "Push-Up"
                        },
                        new
                        {
                            Id = new Guid("171538f1-bd3d-4f69-8a5d-5c80d159d173"),
                            Category = "Chest",
                            Name = "Push-Up Against Wall"
                        },
                        new
                        {
                            Id = new Guid("841f9812-8dc8-4182-8137-411433034919"),
                            Category = "Chest",
                            Name = "Push-Ups With Feet in Rings"
                        },
                        new
                        {
                            Id = new Guid("07aeff38-0985-466b-a406-f953e6597c1a"),
                            Category = "Chest",
                            Name = "Resistance Band Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("bcc228f6-0007-47c4-b215-781347679b7a"),
                            Category = "Chest",
                            Name = "Smith Machine Bench Press"
                        },
                        new
                        {
                            Id = new Guid("5f3d9be3-4ffe-4c94-bb0e-0fe1cc8ed23d"),
                            Category = "Chest",
                            Name = "Smith Machine Incline Bench Press"
                        },
                        new
                        {
                            Id = new Guid("5b02cd89-c570-465d-8b2d-0d577e16936b"),
                            Category = "Chest",
                            Name = "Standing Cable Chest Fly"
                        },
                        new
                        {
                            Id = new Guid("0771a484-fca9-465d-8040-ebea9178e982"),
                            Category = "Shoulder",
                            Name = "Band External Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("9d029e4f-0083-4fb1-a305-9c94e86d7cc0"),
                            Category = "Shoulder",
                            Name = "Band Internal Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("fd806d4c-ab4a-4e37-bf6b-481273564560"),
                            Category = "Shoulder",
                            Name = "Band Pull-Apart"
                        },
                        new
                        {
                            Id = new Guid("148fb42d-ad0a-4e61-8caf-f66a6614acb5"),
                            Category = "Shoulder",
                            Name = "Barbell Front Raise"
                        },
                        new
                        {
                            Id = new Guid("7998e15b-30c7-4b29-a729-664577b182c0"),
                            Category = "Shoulder",
                            Name = "Barbell Rear Delt Row"
                        },
                        new
                        {
                            Id = new Guid("168cab0f-e233-4fb2-be84-d1db85be8148"),
                            Category = "Shoulder",
                            Name = "Barbell Upright Row"
                        },
                        new
                        {
                            Id = new Guid("db4ee30e-84df-4d5e-aa0f-d1ac8a764dd6"),
                            Category = "Shoulder",
                            Name = "Behind the Neck Press"
                        },
                        new
                        {
                            Id = new Guid("79822338-6771-4079-9d75-f6e2c45765fc"),
                            Category = "Shoulder",
                            Name = "Cable Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("2fd15d2e-67d1-44fc-91f8-7667edd66515"),
                            Category = "Shoulder",
                            Name = "Cable Rear Delt Row"
                        },
                        new
                        {
                            Id = new Guid("2c71e76a-06be-44d3-9f1f-18de4c99485c"),
                            Category = "Shoulder",
                            Name = "Dumbbell Front Raise"
                        },
                        new
                        {
                            Id = new Guid("5d38fc58-645b-49d9-815c-62ab0f19b298"),
                            Category = "Shoulder",
                            Name = "Dumbbell Horizontal Internal Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("bb810523-f886-4e5a-a1d9-134c28b5286c"),
                            Category = "Shoulder",
                            Name = "Dumbbell Horizontal External Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("65f3bf41-51a1-4c87-a63d-07af6dd87f67"),
                            Category = "Shoulder",
                            Name = "Dumbbell Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("c65a919c-cb29-4daf-8992-5408d7fc037e"),
                            Category = "Shoulder",
                            Name = "Dumbbell Rear Delt Row"
                        },
                        new
                        {
                            Id = new Guid("ae582b87-2fc8-44be-8eba-98e3888869d2"),
                            Category = "Shoulder",
                            Name = "Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("cd6665e7-2bb2-4c9f-b2c1-dd84c3eadd36"),
                            Category = "Shoulder",
                            Name = "Face Pull"
                        },
                        new
                        {
                            Id = new Guid("c601a369-35f5-4c4b-b0b1-4ddaaa0c403c"),
                            Category = "Shoulder",
                            Name = "Front Hold"
                        },
                        new
                        {
                            Id = new Guid("dcffe063-147c-4f65-b38e-c66062306f5d"),
                            Category = "Shoulder",
                            Name = "Lying Dumbbell External Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("aa13ac8d-7a22-46a1-88c3-69d322fc0d63"),
                            Category = "Shoulder",
                            Name = "Lying Dumbbell Internal Shoulder Rotation"
                        },
                        new
                        {
                            Id = new Guid("0d29c68e-494c-4936-94f7-9aaa233f0a68"),
                            Category = "Shoulder",
                            Name = "Machine Lateral Raise"
                        },
                        new
                        {
                            Id = new Guid("ca9a58ad-36e5-456e-a10d-e0042c3cb96f"),
                            Category = "Shoulder",
                            Name = "Machine Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("0c26b68a-1a0c-49a8-9494-13c2dd7875be"),
                            Category = "Shoulder",
                            Name = "Monkey Row"
                        },
                        new
                        {
                            Id = new Guid("58a50017-31ba-49ab-b2fb-bb5621624157"),
                            Category = "Shoulder",
                            Name = "Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("8354bf9d-42c5-4637-bf82-b5d6f1818ee4"),
                            Category = "Shoulder",
                            Name = "Plate Front Raise"
                        },
                        new
                        {
                            Id = new Guid("c93efc6c-1419-4352-b71d-161e4faf3791"),
                            Category = "Shoulder",
                            Name = "Power Jerk"
                        },
                        new
                        {
                            Id = new Guid("bdcea1ee-00f2-4101-afa2-335bd5fa0bc0"),
                            Category = "Shoulder",
                            Name = "Push Press"
                        },
                        new
                        {
                            Id = new Guid("88e93410-f69b-4041-959c-cfbd26a03403"),
                            Category = "Shoulder",
                            Name = "Reverse Dumbbell Flyes"
                        },
                        new
                        {
                            Id = new Guid("f7a44e94-e8a6-4293-b27e-18253d90d9f7"),
                            Category = "Shoulder",
                            Name = "Reverse Machine Fly"
                        },
                        new
                        {
                            Id = new Guid("eb8f163d-b97f-4334-810b-40214fba5691"),
                            Category = "Shoulder",
                            Name = "Seated Dumbbell Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("35464eab-20fa-4279-bb42-3f680fe563bb"),
                            Category = "Shoulder",
                            Name = "Seated Barbell Overhead Press"
                        },
                        new
                        {
                            Id = new Guid("b4da1602-9a39-4a0c-8461-f91eb94a6fd9"),
                            Category = "Shoulder",
                            Name = "Seated Smith Machine Shoulder Press"
                        },
                        new
                        {
                            Id = new Guid("c01df4a7-f973-4003-8899-395509d52ab7"),
                            Category = "Shoulder",
                            Name = "Snatch Grip Behind the Neck Press"
                        },
                        new
                        {
                            Id = new Guid("77c18141-be95-468c-93ee-d705d46acdf6"),
                            Category = "Shoulder",
                            Name = "Squat Jerk"
                        },
                        new
                        {
                            Id = new Guid("2dfc90d7-5cb2-43a4-be1b-ae36dde4ea11"),
                            Category = "Shoulder",
                            Name = "Split Jerk"
                        },
                        new
                        {
                            Id = new Guid("7ee2349c-8a69-4018-9eb4-08f71b33ffdc"),
                            Category = "Bicep",
                            Name = "Barbell Curl"
                        },
                        new
                        {
                            Id = new Guid("f9be2d18-a4f3-4999-8b88-da858fd26ef1"),
                            Category = "Bicep",
                            Name = "Barbell Preacher Curl"
                        },
                        new
                        {
                            Id = new Guid("41fb04ae-76b0-4c8f-8264-b7a8d087eb8f"),
                            Category = "Bicep",
                            Name = "Bodyweight Curl"
                        },
                        new
                        {
                            Id = new Guid("49e73689-bc44-4259-9268-d9bc5ba1039e"),
                            Category = "Bicep",
                            Name = "Cable Curl With Bar"
                        },
                        new
                        {
                            Id = new Guid("33f6e7b5-8ab1-4479-8fab-2b3a7222c1b5"),
                            Category = "Bicep",
                            Name = "Cable Curl With Rope"
                        },
                        new
                        {
                            Id = new Guid("1b953cc9-cfd8-4d42-972a-3231ca261d02"),
                            Category = "Bicep",
                            Name = "Concentration Curl"
                        },
                        new
                        {
                            Id = new Guid("1f597490-20db-4c73-a685-bfc141ee99d9"),
                            Category = "Bicep",
                            Name = "Dumbbell Curl"
                        },
                        new
                        {
                            Id = new Guid("e6d9729f-19a3-41b3-9feb-fc80d817b66a"),
                            Category = "Bicep",
                            Name = "Dumbbell Preacher Curl"
                        },
                        new
                        {
                            Id = new Guid("58f19d13-386d-4cec-9a49-638b44df9333"),
                            Category = "Bicep",
                            Name = "Hammer Curl"
                        },
                        new
                        {
                            Id = new Guid("c75f032a-1e8d-454b-8a67-f2f86d29fd91"),
                            Category = "Bicep",
                            Name = "Incline Dumbbell Curl"
                        },
                        new
                        {
                            Id = new Guid("598dbdee-684d-4b84-a485-bc260b4b55de"),
                            Category = "Bicep",
                            Name = "Machine Bicep Curl"
                        },
                        new
                        {
                            Id = new Guid("77bc4c7b-1c2d-41ef-9a7c-cd8315af040b"),
                            Category = "Bicep",
                            Name = "Spider Curl"
                        },
                        new
                        {
                            Id = new Guid("643fcd91-ffd7-443b-aa07-43fea276177f"),
                            Category = "Tricep",
                            Name = "Barbell Standing Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("708ace27-4dfa-43a5-9419-4eb7ef1c0a0b"),
                            Category = "Tricep",
                            Name = "Barbell Lying Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("868c1034-880d-4d21-8fae-971a68bf3457"),
                            Category = "Tricep",
                            Name = "Bench Dip"
                        },
                        new
                        {
                            Id = new Guid("41f83d10-070f-475b-92e2-1e5c56664941"),
                            Category = "Tricep",
                            Name = "Close-Grip Push-Up"
                        },
                        new
                        {
                            Id = new Guid("b281ac05-5afa-43e8-898f-03dc957cb045"),
                            Category = "Tricep",
                            Name = "Dumbbell Lying Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("3f8f84d6-1848-4bed-a5da-6215f4323b7a"),
                            Category = "Tricep",
                            Name = "Dumbbell Standing Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("6c7fac59-c9b6-414d-9c5d-621d7bcd5c78"),
                            Category = "Tricep",
                            Name = "Overhead Cable Triceps Extension"
                        },
                        new
                        {
                            Id = new Guid("f6673576-4e92-466f-9bb8-3769d1390961"),
                            Category = "Tricep",
                            Name = "Tricep Bodyweight Extension"
                        },
                        new
                        {
                            Id = new Guid("0be3be0d-ba4b-43fb-a85b-5696a4bfd107"),
                            Category = "Tricep",
                            Name = "Tricep Pushdown With Bar"
                        },
                        new
                        {
                            Id = new Guid("d8ebe4d5-8a60-415c-90f9-05da59f810e1"),
                            Category = "Tricep",
                            Name = "Tricep Pushdown With Rope"
                        },
                        new
                        {
                            Id = new Guid("a6f72ee9-8b07-4e20-95c6-f2ba4ebdc5c2"),
                            Category = "Legs",
                            Name = "Air Squat"
                        },
                        new
                        {
                            Id = new Guid("af3ca46e-e3bb-42fd-bdc9-335e5777c654"),
                            Category = "Legs",
                            Name = "Barbell Hack Squat"
                        },
                        new
                        {
                            Id = new Guid("1f404d20-3f1c-4dcf-b636-2999f324b26c"),
                            Category = "Legs",
                            Name = "Barbell Lunge"
                        },
                        new
                        {
                            Id = new Guid("b5f20365-c298-4a9c-990c-35f5571e0aab"),
                            Category = "Legs",
                            Name = "Barbell Walking Lunge"
                        },
                        new
                        {
                            Id = new Guid("b35cfbf7-b26d-4b23-94a9-082d3eb6edad"),
                            Category = "Legs",
                            Name = "Belt Squat"
                        },
                        new
                        {
                            Id = new Guid("f5dd8bb0-9d1c-4db7-bc84-feb48a44bf6a"),
                            Category = "Legs",
                            Name = "Body Weight Lunge"
                        },
                        new
                        {
                            Id = new Guid("051c79a9-162d-4e74-bdc0-f450f6af630d"),
                            Category = "Legs",
                            Name = "Box Squat"
                        },
                        new
                        {
                            Id = new Guid("5e53ae20-d08b-427b-8c20-14ed9793b506"),
                            Category = "Legs",
                            Name = "Bulgarian Split Squat"
                        },
                        new
                        {
                            Id = new Guid("d71b1e4f-752a-4b7b-a5b8-b98c69fa20ba"),
                            Category = "Legs",
                            Name = "Chair Squat"
                        },
                        new
                        {
                            Id = new Guid("ce7b65f3-9248-442d-a2b4-1f55deac27f3"),
                            Category = "Legs",
                            Name = "Dumbbell Lunge"
                        },
                        new
                        {
                            Id = new Guid("18808320-a63b-428e-9d0b-7560c3f11b32"),
                            Category = "Legs",
                            Name = "Dumbbell Squat"
                        },
                        new
                        {
                            Id = new Guid("0b96bd27-b63f-4fa1-8b5a-63ee46ebcef8"),
                            Category = "Legs",
                            Name = "Front Squat"
                        },
                        new
                        {
                            Id = new Guid("b6836fc3-2722-4f15-bf6c-4a18226cda8b"),
                            Category = "Legs",
                            Name = "Goblet Squat"
                        },
                        new
                        {
                            Id = new Guid("997ed233-9301-448f-96b1-7eb7a08fb51b"),
                            Category = "Legs",
                            Name = "Hack Squat Machine"
                        },
                        new
                        {
                            Id = new Guid("9a20b882-ee0f-4efc-9c98-1ac37eb77df9"),
                            Category = "Legs",
                            Name = "Half Air Squat"
                        },
                        new
                        {
                            Id = new Guid("aeb001e4-9ff6-4bb4-974d-ebf45c64041a"),
                            Category = "Legs",
                            Name = "Hip Adduction Machine"
                        },
                        new
                        {
                            Id = new Guid("020dbec6-88dc-407d-a143-6a752798cb88"),
                            Category = "Legs",
                            Name = "Landmine Hack Squat"
                        },
                        new
                        {
                            Id = new Guid("60f3686e-ece4-4bd1-85bd-f4e4f1695aa0"),
                            Category = "Legs",
                            Name = "Landmine Squat"
                        },
                        new
                        {
                            Id = new Guid("7f7d7b5c-667c-4fbd-97e6-7995a40398bf"),
                            Category = "Legs",
                            Name = "Leg Extension"
                        },
                        new
                        {
                            Id = new Guid("2184f984-c84b-4559-8c08-138651c8ffb5"),
                            Category = "Legs",
                            Name = "Leg Press"
                        },
                        new
                        {
                            Id = new Guid("2bdafd89-ff93-4598-9459-bc07599fb037"),
                            Category = "Legs",
                            Name = "Lying Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("2c008989-756f-438a-bdd8-2910c4ca3c83"),
                            Category = "Legs",
                            Name = "Pause Squat"
                        },
                        new
                        {
                            Id = new Guid("9b66c24c-dbd7-44bd-be76-8b92673d9d8a"),
                            Category = "Legs",
                            Name = "Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("7c34d6d2-0ee9-4c30-8c86-ff1f68a3e956"),
                            Category = "Legs",
                            Name = "Safety Bar Squat"
                        },
                        new
                        {
                            Id = new Guid("d63a1b14-af1d-4c14-adf0-ac18acc90250"),
                            Category = "Legs",
                            Name = "Seated Leg Curl"
                        },
                        new
                        {
                            Id = new Guid("60a7a47c-54de-41c9-963a-8e6b0e7e8019"),
                            Category = "Legs",
                            Name = "Shallow Body Weight Lunge"
                        },
                        new
                        {
                            Id = new Guid("5fd6eba4-19a4-4437-8664-7fe9c40829cf"),
                            Category = "Legs",
                            Name = "Side Lunges (Bodyweight)"
                        },
                        new
                        {
                            Id = new Guid("7c8d41f8-ab25-4d2a-a337-feb1aedb576e"),
                            Category = "Legs",
                            Name = "Smith Machine Squat"
                        },
                        new
                        {
                            Id = new Guid("c5e13a34-953e-4fb6-a53a-313bf6edd032"),
                            Category = "Legs",
                            Name = "Squat"
                        },
                        new
                        {
                            Id = new Guid("ece65b4d-10a6-47eb-9458-9968b3b873c8"),
                            Category = "Legs",
                            Name = "Step Up"
                        },
                        new
                        {
                            Id = new Guid("fbdd8aec-313d-4a92-b10a-f0106e7fc5c2"),
                            Category = "Legs",
                            Name = "Step Up"
                        },
                        new
                        {
                            Id = new Guid("bdfaaa8e-73f3-4b3d-b567-7763da727b07"),
                            Category = "Back",
                            Name = "Back Extension"
                        },
                        new
                        {
                            Id = new Guid("0195a832-e02f-4b6f-8b68-82b996d044cd"),
                            Category = "Back",
                            Name = "Barbell Row"
                        },
                        new
                        {
                            Id = new Guid("aa064d10-6084-4d50-887c-8a092d77dde6"),
                            Category = "Back",
                            Name = "Barbell Shrug"
                        },
                        new
                        {
                            Id = new Guid("cda6a5ed-25ec-46b2-a48e-b47a138b6ef6"),
                            Category = "Back",
                            Name = "Block Snatch"
                        },
                        new
                        {
                            Id = new Guid("cbb1304c-4cc6-4440-a06d-6da5270e78ae"),
                            Category = "Back",
                            Name = "Cable Close Grip Seated Row"
                        },
                        new
                        {
                            Id = new Guid("31e73b95-f194-4c99-88c6-5f20d6db60a2"),
                            Category = "Back",
                            Name = "Cable Wide Grip Seated Row"
                        },
                        new
                        {
                            Id = new Guid("2718bc15-cbb7-4154-b493-e4c560577769"),
                            Category = "Back",
                            Name = "Chin-Up"
                        },
                        new
                        {
                            Id = new Guid("e0b10898-2629-48c4-9330-f0c373b5778e"),
                            Category = "Back",
                            Name = "Clean"
                        },
                        new
                        {
                            Id = new Guid("e2d10c6f-30bf-4b1a-b4df-8be1c8d02525"),
                            Category = "Back",
                            Name = "Clean and Jerk"
                        },
                        new
                        {
                            Id = new Guid("5fa8dc38-ba04-4c6d-ae33-de307c73afef"),
                            Category = "Back",
                            Name = "Deadlift"
                        },
                        new
                        {
                            Id = new Guid("8e0457d9-2464-40d2-b9a2-7f55112596ad"),
                            Category = "Back",
                            Name = "Deficit Deadlift"
                        },
                        new
                        {
                            Id = new Guid("2c89c5f6-2b61-4135-9f0b-66eb973433d8"),
                            Category = "Back",
                            Name = "Dumbbell Deadlift"
                        },
                        new
                        {
                            Id = new Guid("1a693bdf-98dd-48bc-895b-cd39477b851c"),
                            Category = "Back",
                            Name = "Dumbbell Row"
                        },
                        new
                        {
                            Id = new Guid("29fa82b8-544f-4fbf-a9f3-48acea9a3043"),
                            Category = "Back",
                            Name = "Dumbbell Shrug"
                        },
                        new
                        {
                            Id = new Guid("86ed4039-fd53-4530-b4cf-f8614120e47a"),
                            Category = "Back",
                            Name = "Floor Back Extension"
                        },
                        new
                        {
                            Id = new Guid("da6fa21f-9422-4487-94b5-3f72183ae390"),
                            Category = "Back",
                            Name = "Good Morning"
                        },
                        new
                        {
                            Id = new Guid("5185fdfc-8840-46a7-b8cf-1b8cb0c0c999"),
                            Category = "Back",
                            Name = "Hang Clean"
                        },
                        new
                        {
                            Id = new Guid("3f751e15-fbec-414b-b250-278d662c35d1"),
                            Category = "Back",
                            Name = "Hang Power Clean"
                        },
                        new
                        {
                            Id = new Guid("7cd2ff93-c339-4e07-9545-2b644499f4c2"),
                            Category = "Back",
                            Name = "Hang Power Snatch"
                        },
                        new
                        {
                            Id = new Guid("45e7897b-ee56-4135-949e-abd3d65a6a78"),
                            Category = "Back",
                            Name = "Hang Snatch"
                        },
                        new
                        {
                            Id = new Guid("b9dadb6e-e562-4c60-a996-077441e7aaba"),
                            Category = "Back",
                            Name = "Inverted Row"
                        },
                        new
                        {
                            Id = new Guid("d946c68b-368c-4361-b7d7-858a1eb2f3d2"),
                            Category = "Back",
                            Name = "Inverted Row with Underhand Grip"
                        },
                        new
                        {
                            Id = new Guid("14b00c40-7f25-49b0-8e9d-b032babda43b"),
                            Category = "Back",
                            Name = "Kettlebell Swing"
                        },
                        new
                        {
                            Id = new Guid("da5120aa-9f08-479e-89bc-52ab7dde4aa2"),
                            Category = "Back",
                            Name = "Lat Pulldown With Pronated Grip"
                        },
                        new
                        {
                            Id = new Guid("c9542f7a-b9a5-478f-86a8-6b7b9c6a4258"),
                            Category = "Back",
                            Name = "Lat Pulldown With Supinated Grip"
                        },
                        new
                        {
                            Id = new Guid("eee56879-3588-46f1-9ad8-50c6c68d4a54"),
                            Category = "Back",
                            Name = "One-Handed Cable Row"
                        },
                        new
                        {
                            Id = new Guid("0afca2c5-dd1c-4840-b19a-a07cd19be991"),
                            Category = "Back",
                            Name = "One-Handed Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("d1256f14-3a35-451f-b59d-b98ea1f7adfe"),
                            Category = "Back",
                            Name = "Pause Deadlift"
                        },
                        new
                        {
                            Id = new Guid("08e841a3-37e2-4502-a6c2-5933c267d5ec"),
                            Category = "Back",
                            Name = "Pendlay Row"
                        },
                        new
                        {
                            Id = new Guid("d910fad4-24b0-47d8-9aff-3c59f78da81f"),
                            Category = "Back",
                            Name = "Power Clean"
                        },
                        new
                        {
                            Id = new Guid("275350af-74c6-41e8-9b39-53bd02a96f8a"),
                            Category = "Back",
                            Name = "Power Snatch"
                        },
                        new
                        {
                            Id = new Guid("9541112a-e24a-4f6b-9e9a-95a2292fa3fd"),
                            Category = "Back",
                            Name = "Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("3d64e4db-1f54-417a-82b6-c357bc392f45"),
                            Category = "Back",
                            Name = "Rack Pull"
                        },
                        new
                        {
                            Id = new Guid("cee22187-0749-4c54-98cd-08699a2194c5"),
                            Category = "Back",
                            Name = "Seal Row"
                        },
                        new
                        {
                            Id = new Guid("44ceae4e-9697-4e4d-ae26-abf4b080c754"),
                            Category = "Back",
                            Name = "Seated Machine Row"
                        },
                        new
                        {
                            Id = new Guid("bc9f38b0-6b86-4402-b64b-fae920f82eb2"),
                            Category = "Back",
                            Name = "Snatch"
                        },
                        new
                        {
                            Id = new Guid("8b82e7b8-8108-4064-b6ac-9b7ad77e94bf"),
                            Category = "Back",
                            Name = "Snatch Grip Deadlift"
                        },
                        new
                        {
                            Id = new Guid("cb6c99d4-e472-4828-85c5-9ce2d6f37923"),
                            Category = "Back",
                            Name = "Stiff-Legged Deadlift"
                        },
                        new
                        {
                            Id = new Guid("82fd2301-32ea-4f0f-82a4-80ac13d4854b"),
                            Category = "Back",
                            Name = "Straight Arm Lat Pulldown"
                        },
                        new
                        {
                            Id = new Guid("97bec9ba-c9e7-4826-9db4-c83524d1bdf6"),
                            Category = "Back",
                            Name = "Sumo Deadlift"
                        },
                        new
                        {
                            Id = new Guid("9ef8f0a5-616f-4c9a-a89c-72ed25c82cf2"),
                            Category = "Back",
                            Name = "T-Bar Row"
                        },
                        new
                        {
                            Id = new Guid("20bdbda2-57e6-4cdd-8bca-9673045c734d"),
                            Category = "Back",
                            Name = "Trap Bar Deadlift With High Handles"
                        },
                        new
                        {
                            Id = new Guid("8de64c24-59b2-44b5-8133-abb52a25835e"),
                            Category = "Back",
                            Name = "Trap Bar Deadlift With Low Handles"
                        },
                        new
                        {
                            Id = new Guid("86e2400b-7e4a-4b35-b728-1d6bbd8543ac"),
                            Category = "Glutes",
                            Name = "Banded Side Kicks"
                        },
                        new
                        {
                            Id = new Guid("6e89286f-8143-4c9d-b6e3-c1d6257ef0c2"),
                            Category = "Glutes",
                            Name = "Cable Pull Through"
                        },
                        new
                        {
                            Id = new Guid("869ce2b8-93f3-45c5-93f6-89db958b862f"),
                            Category = "Glutes",
                            Name = "Clamshells"
                        },
                        new
                        {
                            Id = new Guid("8659e390-937b-4c90-8204-05e943b1610c"),
                            Category = "Glutes",
                            Name = "Dumbbell Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("a365cf55-0c7d-42ec-8a26-a5d609295bfb"),
                            Category = "Glutes",
                            Name = "Dumbbell Frog Pumps"
                        },
                        new
                        {
                            Id = new Guid("f59dda33-f215-4b6f-bf77-4c3c2bf78bec"),
                            Category = "Glutes",
                            Name = "Fire Hydrants"
                        },
                        new
                        {
                            Id = new Guid("7bf7f9ed-b4ba-4429-bce5-39bcf2bab6fa"),
                            Category = "Glutes",
                            Name = "Frog Pumps"
                        },
                        new
                        {
                            Id = new Guid("43ee40ac-86cc-4a97-aa41-8b15bbd52044"),
                            Category = "Glutes",
                            Name = "Glute Bridge"
                        },
                        new
                        {
                            Id = new Guid("99b07bd3-1516-44d5-b09f-aba231b25cfa"),
                            Category = "Glutes",
                            Name = "Hip Abduction Against Band"
                        },
                        new
                        {
                            Id = new Guid("1ebfff2f-983c-4284-9a6c-e28480ae7aa0"),
                            Category = "Glutes",
                            Name = "Hip Abduction Machine"
                        },
                        new
                        {
                            Id = new Guid("09cd1404-1ad1-4863-b178-a59c5fe3bce5"),
                            Category = "Glutes",
                            Name = "Hip Thrust"
                        },
                        new
                        {
                            Id = new Guid("5681e267-ee5c-47cb-9713-4167746c06e1"),
                            Category = "Glutes",
                            Name = "Hip Thrust Machine"
                        },
                        new
                        {
                            Id = new Guid("c26e55ea-945f-4f9c-91c5-ae36a06a0637"),
                            Category = "Glutes",
                            Name = "Hip Thrust With Band Around Knees"
                        },
                        new
                        {
                            Id = new Guid("6be6f932-5431-4e83-b591-46ff91a06ad8"),
                            Category = "Glutes",
                            Name = "Lateral Walk With Band"
                        },
                        new
                        {
                            Id = new Guid("fc6ed00a-b7f4-4a2a-8629-208ec3eec8ce"),
                            Category = "Glutes",
                            Name = "Machine Glute Kickbacks"
                        },
                        new
                        {
                            Id = new Guid("f558b0e1-d154-4b18-a85b-dd29130e24ce"),
                            Category = "Glutes",
                            Name = "One-Legged Glute Bridge"
                        },
                        new
                        {
                            Id = new Guid("556bea9c-c390-43eb-983d-5c936426fdca"),
                            Category = "Glutes",
                            Name = "One-Legged Hip Thrust"
                        },
                        new
                        {
                            Id = new Guid("8dd315f0-6717-476d-a84e-3873fef8cf28"),
                            Category = "Glutes",
                            Name = "Single Leg Romanian Deadlift"
                        },
                        new
                        {
                            Id = new Guid("89be0df6-0a43-42b2-b025-c41021840f03"),
                            Category = "Glutes",
                            Name = "Standing Glute Kickback in Machine"
                        },
                        new
                        {
                            Id = new Guid("e0b1048b-2996-46d1-80e2-0f413d854e2d"),
                            Category = "Glutes",
                            Name = "Step Up"
                        },
                        new
                        {
                            Id = new Guid("7148656d-2127-486f-a184-385c865a0bf4"),
                            Category = "Abs",
                            Name = "Cable Crunch"
                        },
                        new
                        {
                            Id = new Guid("1c6c480b-1bfb-475c-a251-c566eca15713"),
                            Category = "Abs",
                            Name = "Crunch"
                        },
                        new
                        {
                            Id = new Guid("7638e619-71af-4ed6-9c08-c09e69b156e9"),
                            Category = "Abs",
                            Name = "Dead Bug"
                        },
                        new
                        {
                            Id = new Guid("8f670c50-0a69-4164-8110-42baba5f84ae"),
                            Category = "Abs",
                            Name = "Hanging Leg Raise"
                        },
                        new
                        {
                            Id = new Guid("1124f543-56fa-47fd-9aff-93c92cba3f69"),
                            Category = "Abs",
                            Name = "Hanging Knee Raise"
                        },
                        new
                        {
                            Id = new Guid("d8c180fa-947f-4272-a59d-53fdfdc63be2"),
                            Category = "Abs",
                            Name = "Hanging Sit-Up"
                        },
                        new
                        {
                            Id = new Guid("ae189018-e101-43f0-ab3f-79fb8287c903"),
                            Category = "Abs",
                            Name = "High to Low Wood Chop with Band"
                        },
                        new
                        {
                            Id = new Guid("4181a217-c83e-46e4-9701-dbdb7304b6d4"),
                            Category = "Abs",
                            Name = "Horizontal Wood Chop with Band"
                        },
                        new
                        {
                            Id = new Guid("71f76ec7-a6ca-4b6d-b5a6-5b633e19bdf1"),
                            Category = "Abs",
                            Name = "Kneeling Ab Wheel Roll-Out"
                        },
                        new
                        {
                            Id = new Guid("482cd1d2-aca5-4588-8e65-2fd31c395e7f"),
                            Category = "Abs",
                            Name = "Kneeling Plank"
                        },
                        new
                        {
                            Id = new Guid("2bef41ee-826f-4b08-b4ea-60cf237093ca"),
                            Category = "Abs",
                            Name = "Kneeling Side Plank"
                        },
                        new
                        {
                            Id = new Guid("5b44873f-c84d-4786-b014-580eb0a8242b"),
                            Category = "Abs",
                            Name = "Lying Leg Raise"
                        },
                        new
                        {
                            Id = new Guid("ae15bb14-b103-4442-a4d6-e70fe28e69e5"),
                            Category = "Abs",
                            Name = "Lying Windshield Wiper"
                        },
                        new
                        {
                            Id = new Guid("73f71447-3db2-4849-bfb4-57aaa3fdb3f1"),
                            Category = "Abs",
                            Name = "Lying Windshield Wiper with Bent Knees"
                        },
                        new
                        {
                            Id = new Guid("fa76314b-4800-405c-a586-b6be7c8aadf6"),
                            Category = "Abs",
                            Name = "Machine Crunch"
                        },
                        new
                        {
                            Id = new Guid("4091072b-c826-4a0c-85da-65c442cb20a9"),
                            Category = "Abs",
                            Name = "Mountain Climbers"
                        },
                        new
                        {
                            Id = new Guid("7d2195f8-44e8-4120-b372-48daaef4b88a"),
                            Category = "Abs",
                            Name = "Oblique Crunch"
                        },
                        new
                        {
                            Id = new Guid("c5323025-ac01-4d8c-b8fb-8929c38a1e9f"),
                            Category = "Abs",
                            Name = "Oblique Sit-Up"
                        },
                        new
                        {
                            Id = new Guid("30f73001-2ab0-492a-b5b2-7db21cf0a478"),
                            Category = "Abs",
                            Name = "Plank"
                        },
                        new
                        {
                            Id = new Guid("800af0ad-03b7-431d-97ea-471094f7bef3"),
                            Category = "Abs",
                            Name = "Side Plank"
                        },
                        new
                        {
                            Id = new Guid("347400f2-7b3b-409b-a8b6-9dfd26f042c4"),
                            Category = "Abs",
                            Name = "Sit-Up"
                        },
                        new
                        {
                            Id = new Guid("1571f5c7-cb1b-4232-92e6-921c8ff53c4f"),
                            Category = "Calves",
                            Name = "Eccentric Heel Drop"
                        },
                        new
                        {
                            Id = new Guid("e71207f0-4897-4381-ad59-f74ec79e3c1b"),
                            Category = "Calves",
                            Name = "Heel Raise"
                        },
                        new
                        {
                            Id = new Guid("8520e565-8c06-4968-b621-e6360eb1988e"),
                            Category = "Calves",
                            Name = "Seated Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("2827b667-0232-4943-8195-fa6c69e9d114"),
                            Category = "Calves",
                            Name = "Standing Calf Raise"
                        },
                        new
                        {
                            Id = new Guid("95cb9196-9d41-42db-9b28-519ffda00126"),
                            Category = "Forearms",
                            Name = "Barbell Wrist Curl"
                        },
                        new
                        {
                            Id = new Guid("b027c1cd-90ed-4e8a-8d0e-6d479dfd5972"),
                            Category = "Forearms",
                            Name = "Barbell Wrist Curl Behind the Back"
                        },
                        new
                        {
                            Id = new Guid("2a5fa146-00ef-49e3-8f2b-eb9e8f1d9442"),
                            Category = "Forearms",
                            Name = "Bar Hang"
                        },
                        new
                        {
                            Id = new Guid("5482f7bb-3d29-4a5d-91d7-dae1c1fa434b"),
                            Category = "Forearms",
                            Name = "Dumbbell Wrist Curl"
                        },
                        new
                        {
                            Id = new Guid("2195315e-127b-4329-8e1e-f2986dc5a750"),
                            Category = "Forearms",
                            Name = "Farmers Walk"
                        },
                        new
                        {
                            Id = new Guid("a9d18b6d-6abc-4411-b382-bc072c4d90c3"),
                            Category = "Forearms",
                            Name = "Fat Bar Deadlift"
                        },
                        new
                        {
                            Id = new Guid("a40e150c-4535-4ad4-922c-c6969fdf69f9"),
                            Category = "Forearms",
                            Name = "Gripper"
                        },
                        new
                        {
                            Id = new Guid("a008d5b4-0e42-45bf-84cf-7d5dce3b5085"),
                            Category = "Forearms",
                            Name = "One-Handed Bar Hang"
                        },
                        new
                        {
                            Id = new Guid("37a22e2e-329d-4ffd-9484-8bdb6bbb211a"),
                            Category = "Forearms",
                            Name = "Plate Pinch"
                        },
                        new
                        {
                            Id = new Guid("4d3106fb-2c61-41d9-8f8f-851aa6e03b71"),
                            Category = "Forearms",
                            Name = "Plate Wrist Curl"
                        },
                        new
                        {
                            Id = new Guid("f3fbd829-6834-49e8-aade-4abe533b4637"),
                            Category = "Forearms",
                            Name = "Towel Pull-Up"
                        },
                        new
                        {
                            Id = new Guid("a6bfc80e-6d51-4822-94ac-f2eb42de677a"),
                            Category = "Forearms",
                            Name = "Barbell Wrist Extension"
                        },
                        new
                        {
                            Id = new Guid("988606f6-4e9a-4b3e-b0c8-66d585c10213"),
                            Category = "Forearms",
                            Name = "Dumbbell Wrist Extension"
                        });
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.LogMessageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CssClass")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("MessageDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("WorkoutDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("LogMessages");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.RoundModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExerciseName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundNumber")
                        .HasColumnType("int");

                    b.Property<Guid>("WorkoutId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.SetModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Reps")
                        .HasColumnType("int");

                    b.Property<Guid>("RoundId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SetNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("Weight")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("RoundId");

                    b.ToTable("Sets");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.UserAchievementsModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MainExercises")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PeriodTraining")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalWeightLifted")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TotalWorkoutSessions")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersAchievements");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.UserFriendsModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FriendsString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UsersFriends");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutTemplateExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("WorkoutTemplateModelId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutTemplateModelId");

                    b.ToTable("WorkoutTemplateExercises");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutTemplateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.RoundModel", b =>
                {
                    b.HasOne("WorkoutTrackerWebsite.Models.WorkoutModel", "Workout")
                        .WithMany("Rounds")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.SetModel", b =>
                {
                    b.HasOne("WorkoutTrackerWebsite.Models.RoundModel", "Round")
                        .WithMany("Sets")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Round");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutTemplateExercise", b =>
                {
                    b.HasOne("WorkoutTrackerWebsite.Models.WorkoutTemplateModel", null)
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutTemplateModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.RoundModel", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutModel", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("WorkoutTrackerWebsite.Models.WorkoutTemplateModel", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
